### ISSUE TITLE
Can't initialize reducer with null default state

### ISSUE THREAD

**Issue by bibekg** [mweststrate/immer#102]
I'm trying to set up a reducer to use Immer but keep running into an issue with using a null default state value. When I try loading up the app in browser, I get the following console error:
```
the first argument to produce should be a plain object or array, got object
```
I tried following the code a bit and saw that it's resulting in `isProxyable` returning false on the Redux init process that calls all reducers with `reducer(undefined, "@@redux/INIT")`. My reducer code is below.

```js
const DEFAULT_USER_STATE = null

const userReducer = produce((draft: UserStateType, action: UserActionType) => {
  if (action.type === GET_USER_SUCCESS) {
    draft = action.payload
  } else if (action.type === UPDATE_USER_PROFILE_PIC_SUCCESS) {
    if (draft) { draft.profilePic = action.payload }
  } else if (action.type === MARK_USER_INACTIVE) {
    if (draft) { draft.active = true }
  } else if (action.type === MARK_USER_VERIFIED) {
    if (draft) { draft.verified = true }
  }
})

export default (state: UserStateType = DEFAULT_USER_STATE, action: UserActionType): UserStateType => userReducer(state, action)

```

**Comment by mweststrate** [comment]
Reassigning to `draft = action.payload` is not allowed (it only re-defines the argument name you pass in, but doesn't actually change the draft!).  In your case `action.type === GET_USER_SUCCESS` should be handled outside a producer (so that you can return `action.payload` from the reducer).

Probably we should add a feature allowing returning values from producers :)

**Comment by bibekg** [comment]
Good catch. That doesn't seem to solve the original issue though. The action type that's failing is Redux's initializer, `@@redux/INIT`, which passes `undefined` as the state.

**Comment by mweststrate** [comment]
You should get a clean error about what is wrong with that, did you get an
error?

Op di 20 feb. 2018 00:23 schreef Bibek Ghimire <notifications@github.com>:

**Comment by bibekg** [comment]
Yeah, I wrote the error that I got in the original comment. It's
```
the first argument to produce should be a plain object or array, got object
```

**Comment by bibekg** [comment]
Update: I fixed my problem by wrapping the call to `produce()` in a reducer that ensures that it never passes a `null` or `undefined` as the `state` parameter to `produce()`.

```js
import produce from 'immer'
import {
  GET_USER_SUCCESS,
  UPDATE_USER_PROFILE_PIC_SUCCESS
} from 'actions/types'

const DEFAULT_USER_STATE = null

const userProducer = produce((draft: UserStateType, action: UserActionType) => {
  if (action.type === GET_USER_SUCCESS) {
    draft = action.payload
  } else if (action.type === UPDATE_USER_PROFILE_PIC_SUCCESS) {
    if (draft) { draft.profilePic = action.payload }
  }
})

const userReducer = (state: UserStateType = DEFAULT_USER_STATE, action: UserActionType): UserStateType => {
  if (action.type === GET_USER_SUCCESS) {
    return action.payload
  } else if (state !== null) {
    return userProducer(state, action)
  } else {
    return state
  }
}

export default userReducer
```

**Comment by mweststrate** [comment]
That is the correct fix indeed. But your question inspired me to make this
actually possible in immer OOTB. See the latest commits on master, in the
future you can it without this :)

Op di 20 feb. 2018 om 19:13 schreef Bibek Ghimire <notifications@github.com
