### ISSUE TITLE
Allow returning values from producers

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/immer#103]
Producer could return a value *or* modify a draft. Verify both is never done at the same time. Returning a value can be very useful for default values etc. See several other issues that try to redefine the `draft` object, like #102

**Comment by mweststrate** [comment]
Will be released as 1.1

**Comment by drcmda** [comment]
@mweststrate would it be possible that it detects that if the draft is altered it should simply take the draft and neglect the return value? Having to write out scope blocks sometimes takes more boilerplate than a standard reducer in some cases.

For instance

```jsx
immer(state, draft => draft.count++)
```

would be a clear intent on the programmers side, and immer probably could easily flag the draft as mutated, in which case it shouldn't nag with warnings but simply use the draft.
