### ISSUE TITLE
Specify initial value of reducer

### ISSUE THREAD

**Issue by klimashkin** [mweststrate/immer#105]
Hello!

Sorry if it's been discussed or documented, but I could not find solution.
How to specify initial value of reducer in case of currying?

If on first `@@redux/INIT` run I don't do anything with draft, redux complains about `returned undefined during initialization. If the state passed to the reducer is undefined, you must explicitly return the initial state..` But if I do
```
some: produce((draft, action) => {
    if (draft === undefined) {
      return {};
    }
}
```
redux throw the same error... 
Using version `1.1.0`, and I though that returning object from producers should already work, strange.

**Comment by mweststrate** [comment]
Hi Paul, could you set up a minimal reproduction in a codesandbox?

Op wo 21 feb. 2018 om 09:24 schreef Paul Klimashkin <
notifications@github.com>:

**Comment by klimashkin** [comment]
Created simple pen where returning from currying doesn't work:
https://codepen.io/klimashkin/pen/aqGgor?editors=0010

I found in the doc:
> One think to keep in mind; you cannot use this construction to initialize an uninitialized state. E.g. draft = {} doesn't do anything useful.

Seems like the only way is to pass initial value on store startup, but it's not convenient in redux world.
What if initial value could be passed as second parameter to curry function like for `array.reduce`?
Like
```javascript
const counter = produce((draft, action) => {  
  switch (action.type) {
    case 'INCREMENT':
      return draft.count += 1;
    case 'DECREMENT':
      return draft.count -= 1;
  }
}, {count: 0});
```

**Comment by mweststrate** [comment]
@klimashkin apologies, this was a bug in the currying! Should be fixed in 1.1.1

**Comment by mweststrate** [comment]
See: https://codesandbox.io/s/j4m8q25363

**Comment by klimashkin** [comment]
Thanks @mweststrate!

What do you think about setting default value as a second parameter of curried `produce`?

**Comment by mweststrate** [comment]
@klimashkin could you open a separate issue for that?
