### ISSUE TITLE
Async/Await support

### ISSUE THREAD

**Issue by graphaty** [mweststrate/immer#108]
Would it be possible to add async/await support in the producers? I'm creating a little state management library for personal use with the new context API and would like to bake in immer for immutable mutations.
I think the following typescript snippet demonstrates my use-case well:

```
import immer from "immer"

const test = async () =>
{
	interface Todo
	{
		description: string,
		done: boolean
	}

	interface State { todos: Todo[] }

	const initialState : State = {
		todos: [
			{
				description: "Use immer",
				done: true
			}
		]
	}

	const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))

	const addTodo = (todo: Todo) => async (state: State) =>
	{
		await wait(500) //await ajax call or sth
		state.todos.push(todo)
	}

	const newTodo : Todo = {
		description: "Await async await support",
		done: false
	}

	const newState = await immer(initialState, addTodo(newTodo))
}

test()
```

Currently the library throws: `TypeError: Cannot perform 'get' on a proxy that has been revoked`

Here is a [codesandbox](https://codesandbox.io/s/p7zwo6n207 ).

**Comment by mweststrate** [comment]
No, supporting async / await would break the mental model, as that means that multiple producer calls could interleave with each other and it becomes impossible to reason about what happens. For example what happens if one producer didn't see the state produced by another one because it didn't finalize the proxies yet? Then you would suddenly loose state...

Just use produce (or curried producers) at every 'tick'

e.g. something along these lines

```javascript
const adder = produce((draft, Todo) => {
  draft.todos.push(Todo)
}

const addTodo = async (state: State, todo: Todo) =>
   await wait(500) //await ajax call or sth
   return adder(state, newTodo)
}

const newState = await addTodo(initialState, addTodo(newTodo))
```

**Comment by ir-fuel** [comment]
Sorry to update this closed ticket, but it's the first result in Google.

There is a document that shows an alternative way of solving this, if you really have to do some async stuff when modifying an object. 

https://github.com/immerjs/immer/blob/master/docs/async.md

**Comment by jasonHzq** [comment]
> Sorry to update this closed ticket, but it's the first result in Google.
> 
> There is a document that shows an alternative way of solving this, if you really have to do some async stuff when modifying an object.
> 
> [immerjs.github.io/immer/docs/async](https://immerjs.github.io/immer/docs/async)

The downside of this approach is that you have to guarantee that the created "draft" won't be modified elsewhere during the async method execution
