### ISSUE TITLE
Is it possible to check which properties were update

### ISSUE THREAD

**Issue by nicknikolov** [mweststrate/immer#110]
Hello, thanks making this.

This is not so much an issue as a question.

Since I saw `immer` uses structural sharing, is there some clever way to use it and check which properties of my state have changed after producing a new instance?

Thank you

**Comment by mweststrate** [comment]
Probably missing the point of the question; but any property that is
strictly equal to the previous property you had didn't change.

Op vr 23 feb. 2018 om 14:17 schreef Nick Nikolov <notifications@github.com>:

**Comment by nicknikolov** [comment]
Yes, my question was more about to see if I am missing something or I just need to iterate my properties (I was worried could be tricky for nested objects) and use strict equal check.

I'm gonna close as this is probably what I'm looking for.

**Comment by mweststrate** [comment]
If you want to compute diffs, there are most probably packages around that
can do that :)

Op vr 23 feb. 2018 om 15:21 schreef Nick Nikolov <notifications@github.com>:
