### ISSUE TITLE
Cannot perform get on revoked proxy error when no recursion

### ISSUE THREAD

**Issue by TrueWill** [mweststrate/immer#117]
Similar to https://github.com/mweststrate/immer/issues/100, I'm getting
`TypeError: Cannot perform 'get' on a proxy that has been revoked`
from a test after converting a reducer to immer.

I narrowed the code down from the [original](https://github.com/TrueWill/embracer/blob/immer/src/reducers/skillsReducer.js) to a minimal example, which is why it looks odd.

```
export default (state, action) =>
  produce(state, draft => {
    switch (action.type) {
      case types.SET_STARTING_DOTS:
        return draft.availableStartingDots.map(a => a);
      default:
        break;
    }
  });
```

The above reducer will raise the error when given this state and the SET_STARTING_DOTS action:

```
{
    availableStartingDots: [
      { dots: 4, count: 1 },
      { dots: 3, count: 2 },
      { dots: 2, count: 3 },
      { dots: 1, count: 4 }
    ]
}
```

Changing the case to `return state.availableStartingDots.map(a => a);` removes the error.

**Comment by mweststrate** [comment]
@TrueWill I fixed the issue that the result set was not properly finalized. However, I am pretty sure that this reducer is not doing what you intend it to do; you return a sub part of the original state, effectively changing its shape. 

Your reducer now transforms the state: 

```javascript
{
    availableStartingDots: [
      { dots: 4, count: 1 },
      { dots: 3, count: 2 },
      { dots: 2, count: 3 },
      { dots: 1, count: 4 }
    ]
}
```

into 

```javascript
  [
      { dots: 4, count: 1 },
      { dots: 3, count: 2 },
      { dots: 2, count: 3 },
      { dots: 1, count: 4 }
    ]
```

What you probably want is:
```
case types.SET_STARTING_DOTS:
        draft.availableStartingDots = draft.availableStartingDots.map(a => a);
        return
```

**Comment by mweststrate** [comment]
Released as 1.1.3. Thanks for reporting!

**Comment by TrueWill** [comment]
@mweststrate Yep - I changed the shape to keep the example as simple as possible. The original code preserves shape. Thank you! 😃

**Comment by TrueWill** [comment]
Just tested it - works fine! Great job!
