### ISSUE TITLE
Add immer to flow-typed definitions

### ISSUE THREAD

**Issue by bugzpodder** [mweststrate/immer#119]
Currently I ignore everything in node_modules/.* in my flowconfig, and relies on flow-typed for my library definitions.  Unfortunately it means the .flow file distributed from immer is ignored.  

I tried copy the immer.js.flow file directly to my flow-typed directory but it did not work as expected, will need to play around a bit more.  https://github.com/flowtype/flow-typed/

**Comment by mweststrate** [comment]
I think you should fix your project setup. relying on the typings as provided by the library is *much* more reliable compared to fetching them from flow-typed.

**Comment by bugzpodder** [comment]
Its fine if immer won't support flow-typed definitions.  I've made the project setup decisions on purpose and there are definitely real reasons to ignore node_modules (which I won't get into here).  Anyhow using flow-typed lib defs came from an endorsement in the official flow documentation: https://flow.org/en/docs/libdefs/.
