### ISSUE TITLE
Typescript error with producer in latest version: 'expected one arguments, but got two'

### ISSUE THREAD

**Issue by RikuVan** [mweststrate/immer#129]
* [x ] Issue: 
I use produce for a reducer like this
```js
export default (
  state = initialState.search,
  { type, payload }: SearchActions
): Partial<RootState> => (handlers[type] ? produce(handlers[type])(state, payload) : state);
```
 While this still works fine it now raises a Typescript error in the new (1.2) version: 'expected 1 arguments, but got two.'
I looked at the typings and I don't grasp why they don't work as they seem to have an overload for this.
I will try to produce a codepen of the issue in the next day or two.

**Comment by RikuVan** [comment]
example of typescript error: https://codesandbox.io/s/4047no7q77?module=%2Fsrc%2Freducer.ts

**Comment by mweststrate** [comment]
As a work around: `produce<any, any>` will fix it, will see if we need some overload reordering to improve it

**Comment by mweststrate** [comment]
Check, the inference of this producer has changed indeed, however, the current typings are better, as in the old setup even typed producers with arguments would always infer there arguments to `any`. So I'll keep the typings as is, as they, in general, infer better typings. 

So for now, if TS cannot infer the amount and types of arguments of the producer function (like in this example), explicitly type `producer`, like `produce<any, any>(handler)`, ideally, you make the typing more strict by giving as first argument the type of state, and as second generic the type of the `payload`'

To fix the generic case, TS needs support for generic Variadic types: https://github.com/Microsoft/TypeScript/issues/5453

**Comment by RikuVan** [comment]
Thanks for you response. As you suggest, this does the job `produce<UserState, Actions>`
