### ISSUE TITLE
Peculiar behaviour of destructuring

### ISSUE THREAD

**Issue by st-clair-clarke** [mweststrate/immer#132]
Hi,
I have the following:

      @Action( RsRosCoughUiUpdate )
      rsRosCoughUiUpdate( { getState, patchState }: StateContext<IRs>, payload: IFormState ) {
        console.log( `classToPlain(payload) | ${JSON.stringify( classToPlain(payload) ) }` )
        console.log('PAYLOAD', payload)
        console.log('PAYLOAD STATUS', payload.status)
        console.log('PAYLOAD STATUS', payload['status'])
        console.log( `change-before | ${JSON.stringify( payload.change ) }` )
        console.log(classToPlain(payload))
        console.log( `change-after | ${JSON.stringify( payload.change ) }` )
        
        let {change, dirty, pristine, status, target, touched, untouched} = payload
        
        console.log(change, dirty, pristine, status, target, touched, untouched)
        
        const nextState = produce( getState(), draftState => {
          let {change, dirty, pristine, status, target, touched, untouched} = payload
          console.log( `change | ${JSON.stringify( payload.change ) }` )
    //       draftState.ros.ui.cough = payload
    
          
          
    //      draftState.ros.ui.cough =    {...payload}
    //      draftState.ros.ui.cough.change = payload.change
    //      draftState.ros.ui.cough.dirty = payload.dirty
    //      draftState.ros.ui.cough.pristine = payload.pristine
    //      draftState.ros.ui.cough.status = payload.status
    //      draftState.ros.ui.cough.target = payload.target
    //      draftState.ros.ui.cough.touched = payload.touched
    //      draftState.ros.ui.cough.untouched = payload.untouched
        } )
        
        patchState( { ...getState(), ...nextState } )
      }

When the application runs, the console log is shown below:

    classToPlain(payload) | {"payload":{"change":"add","dirty":true,"pristine":false,"status":"INVALID","target":"[cough->rs-ros]cmp","touched":true,"untouched":false}}
    rs.store.ts:73 PAYLOAD RsRosCoughUiUpdate {payload: FormState}
    rs.store.ts:74 PAYLOAD STATUS undefined
    rs.store.ts:75 PAYLOAD STATUS undefined
    rs.store.ts:76 change-before | undefined
    rs.store.ts:77 {payload: {…}}payload: {change: "add", dirty: true, pristine: false, status: "INVALID", target: "[cough->rs-ros]cmp", …}__proto__: Object
    rs.store.ts:78 change-after | undefined
    rs.store.ts:82 undefined undefined undefined undefined undefined undefined undefined
    rs.store.ts:86 change | undefined

Removing all the debug info and performing a `console.log(payload)` gives the following

![debug](https://user-images.githubusercontent.com/3227590/37891244-9857453c-30a1-11e8-82fd-e1de31fb0eee.jpg)

Questions:
1. Why the destructured values always undefined?
2. Why does the dot traversal of the payload object graph always undefined?

Cheers

**Comment by mweststrate** [comment]
@st-clair-clarke I am staring at your code for a while, but it is a bit unclear to me how this relates to immer, as immer isn't doing anything with the `payload` variable? I don't know what `draftState.ros.ui.cough` is, but note that immer does not operate on class instances. To further clarify your problem, please create a minimal, reproducible setup, like a code sandbox or something.

**Comment by mweststrate** [comment]
Closing for the lack of a reproduction
