### ISSUE TITLE
is there a better way to handle `indexOf` 

### ISSUE THREAD

**Issue by slashhuang** [mweststrate/immer#133]
* [ ] I am willing to implement this myself
* [x] Issue:  `indexOf` operator not work for proxy
  * Version: ^1.2.0

```ts
 const state = [{foo: 1}, {bar: 2}];
let payload = state[0];
produce(state, (draft) => {
    let index = draft.indexOf(payload);
    draft[index] = {fooNext: 1},
});
  
```
  * Expected behavior:  get the right index, which is 0
  * Observed behavior:  index producer -1
  * [x] Occurs when using Proxies (use `setUseProxies(true)`)
  
[check it in codesandbox](https://codesandbox.io/s/42k6knjv50)

**Comment by slashhuang** [comment]
maybe not a problem, but I hope immer could have a way to get it right, so that in `draft => any` function, I do not have to touch rawState.

**Comment by mweststrate** [comment]
I think this is a rabbit hole that will go really deep, and should rather
be fixed by improving the docs :)

Op di 27 mrt. 2018 om 09:11 schreef 黄晓刚 <notifications@github.com>:

**Comment by alcovescape** [comment]
Just use `state.indexOf(payload)`, it is a proxy not the original, the object reference are not the same, 

that's why `{} == {} // => false`, they are pointer to different object, even though structurally the same

**Comment by mweststrate** [comment]
closing, as question has been answered
