### ISSUE TITLE
Object value loses key/value inside redux reducer

### ISSUE THREAD

**Issue by alexcroox** [mweststrate/immer#134]
* [x] Issue: Modifying array item doesn't product expected results
  * Version: ^1.2.1
  * _SIMPLE_ Reproduction: 

```
import findIndex from 'lodash.findindex'

const initialState = {
  list: []
}

// Reducer
export default produce(
  (draft, action) => {
    switch (action.type) {
      case PAUSE_TIMER: {
        let timerIndex = findIndex(draft.list, ['id', action.timerId])

        if (timerIndex > -1) {
          let timer = draft.list[timerIndex]

          if (action.pause) {
            if (!timer.paused) {
              timer.endTime = Date.now()
              timer.previouslyElapsed = (Date.now() - timer.startTime) + timer.previouslyElapsed
            }
          } else {
            timer.startTime = Date.now()
          }

          timer.paused = action.pause

          console.log('previouslyElapsed', timer.previouslyElapsed) // This returns 1835
          console.log('draft.list[timerIndex]', draft.list[timerIndex])
        }
      }
    }
  }, initialState
)
```

  * Expected behavior: I expect my redux state for that array index to have `1835` for the `previouslyElapsed` key. 

  * Observed behavior: Instead it removes the key entirely in my redux state, despite verifying it's correct value (through console.log) inside the function at the end.

![ss](https://cl.ly/qd7a/Screen%20Shot%202018-04-04%20at%2008.33.58.png)

![ssredux](https://cl.ly/qdB5/Screen%20Shot%202018-04-04%20at%2008.38.33.png)

  * [x] Occurs when using Proxies (use `setUseProxies(true)`)
  * [ ] Occurs in the ES5 implementation (use `setUseProxies(false)`) I tried this but `previouslyElapsed` gets set with `Exception: Error: Cannot use a proxy that has been revoked. Did you pass an object from inside an immer function to an async process? at assertUnfinished`
  
I'm trying to refactor my app from `seamless-immutable` to `immer` so perhaps I'm missing a technique, but I've poured through the readme and other issues and am stumped!

Thank you

**Comment by mweststrate** [comment]
Can you create a PR with a unit test showing the problem?

Op wo 4 apr. 2018 09:36 schreef Alex <notifications@github.com>:

**Comment by mweststrate** [comment]
Closing for the lack of a reproduction

**Comment by alexcroox** [comment]
Sorry for disappearing I became a father a few weeks ago so been a little distracted. This is still effecting me so I will try reduce to a small test case.
