### ISSUE TITLE
Would you consider not using a default export?

### ISSUE THREAD

**Issue by scriby** [mweststrate/immer#136]
The build environment at work doesn't play well with default exports. I'm wondering if you would consider exporting the produce function as a normal function and requiring calling code to use

import {produce} from 'immer';

Thanks for taking a look!

**Comment by scriby** [comment]
Thanks for the suggestion!

It's not so much an issue of the import, but just that our build system completely forbids code to use default exports. It's one of those massive company things where you don't have much flexibility.

I don't think there's really anything intrinsically wrong with using a default export, but it does get a little stranger to use once the module also exports other things as well (like setAutoFreeze).

**Comment by mweststrate** [comment]
@scriby to clarify, do you want to export it both as default and normal function, or only as normal export?

**Comment by scriby** [comment]
I think it would work for us if immer used a normal export in addition to the default export.

**Comment by mweststrate** [comment]
@scriby feel free to open a PR. Would you be ok that the typings for flow / TS don't support this? I would rather keep this an undocumented feature to avoid confusing by other consumers.

**Comment by scriby** [comment]
I've currently got a patch in our source control for both immer and the typings to add produce as an export. It's not too much harder to maintain both of those than just one of them, so I'd probably just keep maintaining both of them if no changes can be made here.

I don't think I follow why adding a regular export would be confusing. In my opinion `import produce, {setAutoFreeze, setUseProxies} from 'immer';` is more confusing than `import {produce, setAutoFreeze, setUseProxies} from 'immer';`.  I don't see that allowing it to work either way causes harm.

If you're not convinced feel free to close this one out :)

**Comment by Rob-pw** [comment]
On node version `v9.11.1` using the `--experimental-modules` flag I attempt the example stating `import produce from "immer"`, as you describe I tried `import { default as produce } from "immer"` but this results in an object of form `{ default: [Function: produce],  setAutoFreeze: [Function: setAutoFreeze], setUseProxies: [Function: setUseProxies] }` and a `TypeError: produce is not a function`. I am used to imports of the form `import { agoody } from "goodies"` or `import wrappingFunction from "library"`.

There might be some error in my approach, and by not using a build system.

**Comment by hufan-akari** [comment]
I want to use immer through CDN. I have to write `immer.default`, it is not clear.

```js
const baseState = [
    {
        todo: "Learn typescript",
        done: true
    },
    {
        todo: "Try immer",
        done: false
    }
]

const nextState = immer.default(baseState, draftState => {
    draftState.push({todo: "Tweet about it"})
    draftState[1].done = true
})
```

Could we make it better?

**Comment by mweststrate** [comment]
@Rob-pw I can't follow your question. Which variant is working and which isn't?

@hufan-akari No, that is how the module system works, and this keeps it consistent. `import x from y` means `const x = require('y').default` in commonJS. Just put `const produce = immer.default` somewhere in the top of your file and use that.

**Comment by Rob-pw** [comment]
In this case `import x from y means const x = require('y').default` doesn't seem to hold, otherwise we would not need to declare a `const produce = immer.default` afterwards, which works but is a tad awkard. 

`import { produce } from immer` would be ideal for me also.

**Comment by hufan-akari** [comment]
I vote for export named function.
I prefer to use `immer.produce`.

**Comment by abidev** [comment]
I am using Typescript 2.3.3 with moduleResolution "node" `import produce from 'immer'`  &  `import * as prodce from 'immer'` throws compile time error... can any one help me ?

**Comment by abidev** [comment]
@mweststrate Thanks for your time... 
https://github.com/abidev/immer-test, simple repo with just one ts file, Whenever i import immer ngc just shouts `TypeError: Cannot read property text of undefined` just do npm run build after uncommenting any of import style mentioned above

**Comment by mweststrate** [comment]
`produce` is now and named export as well and released as 1.4.0

**Comment by mweststrate** [comment]
@abidev I think there might something with your local setup, or best clear your node_modules, upgrade ode, etc. For me your repository worked just fine:

```
> immer-trail@1.0.0 build /home/michel/Desktop/tmp/immer-test
> ngc -p ./src/tsconfig.json

➜  immer-test git:(master) 
```

For any follow up comments, please open a new issue, as your question is unrelated to this issue.

**Comment by abidev** [comment]
@mweststrate Thanks... will try that

**Comment by scriby** [comment]
Just noticed you took care of this. Thanks!
