### ISSUE TITLE
produceProxy hides the errors

### ISSUE THREAD

**Issue by a-pavlov-parc** [mweststrate/immer#141]
Hi. Thank you for this great library. 

  * [x] Issue: I have a small reducer. There I intentionally have a null reference error `employeeID: item.something.id`. I see the browser doesn't show there is anything wrong, but it doesn't work. After a small investigation, I found the reason of this behavior. The reason [is there is a `try, finally` construction](https://github.com/mweststrate/immer/blob/master/src/proxy.js#L134), but there is no `catch` one. I managed to add a `catch` with `console.error(error)` then it started working as expected and I see the error now
  * Version: 1.2.0
  * Expected behavior: it shows all the errors
  * Observed behavior: It hides the error
  * [x] Occurs when using Proxies (use `setUseProxies(true)`)

**Comment by mweststrate** [comment]
@a-pavlov-parc I don't really understand your issue. Can you turn it into a PR with unit test?

`try .. finally` means that the exceptions are *not* caught by immer, while introducing a `catch` blocks actually eats the errors and makes it impossible to catch them outside. If an error is thrown, but you don't see it back anywhere in the browser, that means that you are eating exceptions *somewhere else*. 

That is, if I understand the question correctly :). If I don't, please show with a test what you are pointing at.

**Comment by mweststrate** [comment]
Closing until a reproduction is available
