### ISSUE TITLE
The first argument of the produce function should be ....

### ISSUE THREAD

**Issue by AndreBastos23** [mweststrate/immer#142]
Hello,

I'm currently trying to refactor a bunch of our reducers using the immer package, but there is a specific reducer that gives this error when trying to call a action creator.

`ERROR Error: the first argument to an immer producer should be a primitive, plain object or array, got object: "[object Object]"`

The current reducer is this:

```
const initialState: IUiState = {
     toastDisplayStatus: false,
     loadingOverlayDisplayStatus: false
};
export const uiReducer = (state = initialState, action) =>
	produce(state, draft => {
		switch (action.type) {
			case UiActions.UPDATE_TOAST:
				draft.toastDisplayStatus = action.payload;
				break;
			case UiActions.UPDATE_OVERLAY:
				draft.loadingOverlayDisplayStatus = action.payload;
				break;
	}
});
```

I have no idea what i'm doing wrong, since this is exactly equal to another reducer that works. 

Does anyone have any idea what i'm doing wrong?

**Comment by mweststrate** [comment]
sounds like your state might be a class instance?

Op di 17 apr. 2018 om 13:12 schreef AndreBastos23 <notifications@github.com

**Comment by AmarnathGangapuram** [comment]
Hi,
I am facing problem at converting setState to useState 
`this.setState(produce(draft => {
                 draft.downloadsData[task.id].total = expectedBytes;
                 draft.downloadsData[task.id].status = 'downloading';
                console.log(downloading start FilePath${filePath});
                }));
            })

`
    how to convert above setState to useState() .I tried but I am getting errors like 
Error: [Immer] The first or second argument to `produce` must be a function.
