### ISSUE TITLE
instead of return use a 2nd argument `replace` for replacing draft.

### ISSUE THREAD

**Issue by alcovescape** [mweststrate/immer#147]
* [x] Feature request: 2nd argument for replacing draft instead of return.
  * [ ] I am willing to implement this myself

Now:
```js
// Error: An immer producer returned a new value *and* modified its draft. Either return a new value *or* modify the draft.
immer([], s => s.push(1));

// this is also error, didn't dive deep in the source code, but it __should__ still be valid.
immer([1,2,3,4], s => s.splice(1, 2));

// this will pass, but completely unintentional.
immer([[1,2,3],[4,5,6]], s => s[0])
```

Desire:
```js
// ok
immer([], s => s.push(1)) 
// use this api instead.
immer([], (s, replace) => replace([...s, 1, 2, 3])) 
```

Motivation:
1. It is an unintuitive behaviour return value imply replace in mutable context, in some cases it happens to randomly work.
2. A runtime check has to be made each time for return value, it is not necessary if the function length is exactly 1. a minor perf improvement.
3. Less Error, More predicability.

* notice this will be a breaking change.

**Comment by mweststrate** [comment]
The first error is correct.

The second error is correct as well, as `splice` will return the collection of removed items, which is something completely different then `s`. You probably meant `s => { s.splice(1, 2) } ` which is something different

The third case, it is unclear what is unintentional about it?

I think the `replace` api as proposed unnecessarily complicates think, without adding real value. Just be aware that in javascript `x => x`  means something different then `x => { x }`
