### ISSUE TITLE
Clone on freeze?

### ISSUE THREAD

**Issue by vorg** [mweststrate/immer#151]
Assigning object to state in Immer 1.0.3 freezes the object. I would expect the resulting state to be frozen, not the source data?

```javascript
const users = [
  { name: "Marcin", id: 0, selected: false },
  { name: "Bob", id: 1, selected: false }
];

const state = {
  selectedUser: null
};

const newState = produce(state, draft => {
  draft.selectedUser = users[0];
});

newState.selectedUser.selected = true; //Expected Error: Attempted to assign to readonly property
users[1].selected = true; // OK
users[0].selected = true; // Not OK, Error: Attempted to assign to readonly property
```

I think i understand why that happens (you want to avoid copying data) but it means `produce` has unexpected sideffects on the rest of my app as it freezes any data it touches.

Sample https://codesandbox.io/s/y5ljyl319

**Comment by BasitAli** [comment]
I don't really know the internals of immer but I think that's the expected behaviour. When you produce a new state, only the parts you modified are updated, the rest of the properties are just written back as it is. When the result is frozen, it causes all the properties to freeze (`user[0]` in your case).

Although you may disable auto-freeze `setAutoFreeze(true / false)`, I modifying/mutating the state directly is an anti-pattern and is exactly why immer auto freezes the object.

**Comment by Sigmus** [comment]
Why would you need to modify your original data? The whole idea is you always modify the produced state, not the original data.

> (...) but it means produce has unexpected sideffects on the rest of my app as it freezes any data it touches.

If the rest of your app needs to modify the original data maybe you could clone the object before producing a new state?

**Comment by vorg** [comment]
Well this is quite big application. I wanted to introduce immer gradually and freezing source data, not just state, has some non trivial side effects. If that’s expected i must have misunderstood the docs. I expected that only state aka objects returned from produce are frozen. Currently I resolved the issue by storing selectedUserId instead if whole user model object.

**Comment by mweststrate** [comment]
freezing can be disabled by using `setAutoFreeze(false)`. 

You understood the docs correctly; only the returned state is frozen. 

Beyond that, as @Sigmus indicitated, if you start to modify either the original or returned data, you break the model of immutability and all guarantees and assumptions you could made before can no longer be made.
