### ISSUE TITLE
Getting the wrapped object from a proxy

### ISSUE THREAD

**Issue by RichieAHB** [mweststrate/immer#153]
Please specify:

(Not filling out _all fields_ of this template will probably result in your issue being closed without further notice. If you are not willing fill it in, why would someone else spent his time fixing it?)

* [x] Feature request: I'm currently using immer to modify a subtree inside a larger tree. I want to be able to find nodes in the subtree using reference equality (rather than the predicate I'm currently using due to the proxy), modify that node in the tree then validate the whole tree. Would you be willing to accept a PR that basically allows you to get the wrapped object from the Proxy (in this case a nested proxy, not the root Proxy)? Otherwise maybe a tiny helper like `eq(predicateObj, proxyObj)` that will do the unwrapping and checking?
  * [x] I am willing to implement this myself

**Comment by RichieAHB** [comment]
This is verbatim code but basically it would be nice if `targetPredicate` could be a function that `===` compares two objects. I'd also like to be able to quickly get a reference to the new part in the tree outside of produce (but I'm considering just putting a `Symbol` on the update node in the tree and using that, rather than the original predicate, to find the node again after update). Hope this makes sense!

```
const createProduce = modifier => validator => (
  model,
  targetPredicate,
  ...args
) => dispatch => {
  const newModel = produce(model, draftModel => {
    const targetInfo = find(draftModel, targetPredicate);
    if (!targetInfo) {
      throw new Error(`Couldn't find target`);
    }
    modifier(targetInfo, ...args);
  });

  const errors = validator(newModel);
  const valid = !errors.length;
  // TODO: try and avoid one of these two `find` calls
  const targetInfo = find(newModel, targetPredicate);
  dispatch &&
    dispatch(valid ? newModel : model, valid && targetInfo, !valid && errors);
  return valid;
};
``

**Comment by RoboPhred** [comment]
I came across the need for this as well today.  I am using immer for my internal state management, but I have sub-reducers provided by an external source.  I would like to act like pure-redux to the outside world, but as-is I cannot pass them a non-mutable state.

I essentially have something like this
```
for (const thing of things) {
  const oldState = state.thingStates[thing.id];
  const reducer = thingDef[thing.type].reducer;

  // Issue is here: I want to pass a non-proxy / frozen state to the reducer, as the usage
  // of immer is an implementation detail that the external reducer should not expect or rely on.
  const newState = reducer(oldState || {});

  state.thingStates[thing.id] = newState;
}
```

An additional complexity is that this is being done in another loop, processing batched operations.  It is expected that there will be multiple reducer calls on the same state object.  Because of this, I cannot use the initial outer state without having to recalculate it each time or nesting the use of immer.

It would be nice if there was a way to actualize a current version of a nested object in the draft.
I would imagine this would be analogous to the use of .toJS() in Immutable.js

**Comment by mweststrate** [comment]
@RichieAHB when working with immutable data structures, you should never rely on reference equality of objects, that model breaks as soon as anything fancies happen, (being immer, or some middleware that does other stuff in the mean time etc). I recommend to pass along id's instead. 

Alternatively you could perform the search in the original model, and the run immer just on that model and then merge it back to the original. But I would go for the first option.

For `eq` you can basically pick any deep equality function, there is no need to just another implementation of that to immer (a proper implementation would probably be half of the immer size ;-)). 

That being said, feel free to introduce a function that given a draft returns the original object, it shouldn't be that hard and is probably convenient for other situations as well like change detection.  Maybe call it `original`?

@RoboPhred what you are describing doesn't sound like the same issue, please open a new one. But what you are describing doesn't sound like a reducer at all in the first place :) If a reducers requires its base state to be mutable, that means it has side effects and ain't a reducer.

**Comment by RichieAHB** [comment]
I am actually doing it for finding nodes in the tree but also, ensuring the
state is the same (hence the reference equality is ideal for me here). I’ll
open a PR for an `original` function if that’s cool :)

**Comment by mweststrate** [comment]
@RichieAHB sure, welcome!

**Comment by RIP21** [comment]
Since it merged it should be closed :P @mweststrate

**Comment by mweststrate** [comment]
Doh!
