### ISSUE TITLE
Feature request: export createProxy and finalize methods

### ISSUE THREAD

**Issue by jwickens** [mweststrate/immer#159]
Please specify:

* [x ] Feature request: ~~thenable producer~~ export  createProxy and finalize
  * [x ] I am willing to implement this myself

I would like to use immer to implement something like the following

```js
MyModel.record.a = 12
await somethingElse()
MyModel.record.b = 13
await MyModel.save()
```

Where record is the proxy, and calling save finalizes the output of the producer.

To be clear, Im not requesting the above API in immer.

**Comment by jwickens** [comment]
Just thinking about this more rather than modifying the producer api to support promises I think I could just use this line from proxy.js
https://github.com/mweststrate/immer/blob/537aa92f4daa290ca97dfcbac72701c836f536aa/src/proxy.js#L142

To get the member of "MyModel" setup with the immer proxy

and the use "finalize" from common.js for the "MyModel.save()"

So the issue then would be exporting the relevant functions to make a proxy and to finalize it from the package.

(Going to edit the title given this)

**Comment by mweststrate** [comment]
If you want to update state asynchronously, just run `produce` twice, there is no need to keep the produce "open". If you don't want to be affected by changes in the mean time. 

```
state = produce(state, d => { d.record.a = 12 })
await somethingElse()
state = produce(state, d => { d.record.b = 13 })
// etc
```

See also https://github.com/mweststrate/immer/issues/169 for a similar question

**Comment by jwickens** [comment]
Hmm, ok that makes since. I still think having the createProxy and finalize functions available so that the proxy can be used outside of the recipe function scope. Are those functions that you think would make sense to expose in the immer package?

**Comment by mweststrate** [comment]
Nope, the whole point of immer is that the drafts are only modifyable at a very strict point in time, and are useless outside it, as it are the immutable states that should drive  your app, not the drafts.
