### ISSUE TITLE
Feature request: support JSON Patch

### ISSUE THREAD

**Issue by malash** [mweststrate/immer#160]
Please specify:

* [x] Feature request: support JSON Patch
  * [x] I am willing to implement this myself

Any plan to support the [JSON Patch](http://jsonpatch.com/) specified in [RFC 6902](http://tools.ietf.org/html/rfc6902) ?

**Comment by mweststrate** [comment]
mobx-state-tree supports json-patch OOTB :)

Op di 5 jun. 2018 om 05:26 schreef Braden Napier <notifications@github.com>:
