### ISSUE TITLE
Adding Property to Object in Array Not Working

### ISSUE THREAD

**Issue by Nick-t-go** [mweststrate/immer#163]
* Version: 1.3.1
* [x] Issue: 
  Trying to add a property to objects that are unfortunately pretty deep into the state tree. Instead of having the property added to the object it replaces the entire object i.e I lose all other properties on the object. I am doing something wrong but not sure what it is. The problem occurs for the SET_LAYOUT_AREA case in the following reducer:
```
   const Pages = (state = {isFetching: false,collection: {},current: null}, action) =>
     produce(state, draft => {
    switch(action.type){
      case RECEIVED_PAGE:
        draft.isFetching = false;
        draft.collection[action.page.id] = action.page;
        draft.currentPage = action.page.id;
        return;
      case SET_CURRENT_PAGE:
        draft.current = action.id;
        return;
      case SET_LAYOUT_AREA:
        draft.collection[action.id].layout_json.forEach((boxLayout, idx) => {
          boxLayout.area = action.layouts[boxLayout.uid];
        });
        return;
      default:
        return;
  }
});
```
  * Expected behavior:  I expect it to return the original object with an added property of area. ex:
     `[{existingProp1: data, existingProp2 :data, area: 1234}...]`
  * Observed behavior:  I observed that it only returns the area property and I lose all other properties:
     ` [{ area: 1234}....]`
  * [x] Occurs when using Proxies (use `setUseProxies(true)`)

**Comment by mweststrate** [comment]
Closing for the lack of a reproduction
