### ISSUE TITLE
Multiple set state call fail

### ISSUE THREAD

**Issue by kduy969** [mweststrate/immer#164]
Immer version:1.3.0
React version: 16.3.2

My page contain a dropdown ( response to state.dropdownOpen ), when I click on user item on dropdown will open a profile modal ( response to state.openProfileModal).

The problem is when I click on "user item" this.toggleProfile() will be call, but this.toogleDropdown() will be call after that ( because every time an item is clicked, the dropdown will try to close itself ). This will make 2 subsequent call of setState, and I found out only the last one ( toggleDropdown ) make effect. Result is modal is not showup but the dropdown is closed.

```
toggleDropdown() {
    this.setState(produce(this.state, (draft) => {
      draft.dropdownOpen = !draft.dropdownOpen;
    }));
  }
toggleProfileModal() {
    this.setState(produce(this.state, (draft) => {
      draft.openProfileModal = !draft.openProfileModal;
    }));
  }
render(){
 return 
    <div>
      <EditModal 
                 open={this.state.openProfileModal} toggle={this.toggleProfileModal}/>
      <Dropdown
                 open={this.state.dropdownOpen} toggle={this.toggleDropdown}/>
    </div>
}
```

**Comment by mweststrate** [comment]
`setState` is async, so to update based on the previous scheduled state one should use `this.setState(state => produce(state, draft => {}))`

**Comment by kduy969** [comment]
Thanks, your solution work, and to be safe, I think while using immer I should change all
```
this.setState(produce(this.state, draft => {}))
```
to
```
this.setState(state => produce(state, draft => {}))
```
right ?
because multiple setState call sometime happen unexpectedly.
Only 1 more question: does this approach affect performance

**Comment by mweststrate** [comment]
Whether it affects performance doesn't doesn't matter until you can proof
otherwise 😊

Op wo 27 jun. 2018 18:33 schreef kduy969 <notifications@github.com>:

**Comment by kduy969** [comment]
Thanks, I will figure out later.
