### ISSUE TITLE
setTimeout and immer

### ISSUE THREAD

**Issue by giorgi-m** [mweststrate/immer#169]
* Reproduction: https://codesandbox.io/s/k3r79vm813 
  * Expected behavior: increase the bday value
  * Observed behavior: I get an error:  "Uncaught TypeError: Cannot perform 'get' on a proxy that has been revoked at eval"

Is my understanding correct and setTimeout inside produce doesn't work out well?
e.g. this code raises error as specified below:

```
 this.setState(
      produce(this.state, draft => {
        setTimeout(() => {
          draft.user.age += 1;
        }, 1000);
      })
    );  
```
Error

> Uncaught TypeError: Cannot perform 'get' on a proxy that has been revoked at eval

**Comment by mweststrate** [comment]
You cant do stuff async like that, the producer already returned before your timeout runs. Basically you would be modifying an object nobody has a reference to anymore. And to fail fast on that the proxy get's revoked.

Instead, swap the whole thing around; put the setState & produce inside your setTimeout.

**Comment by giorgi-m** [comment]
@mweststrate I see but that swapping wouldn't be easy if theoretically I wanted something like this:
```

 this.setState(
      produce(this.state, draft => {
      draft.a=1;
      setTimeout(() => {
          draft.user.age += 1;
        }, 1000);
      draft.b=2;
      })
    );  

```
isn't it?

**Comment by mweststrate** [comment]
You should call setState twice if you want to set your state twice

Op za 21 jul. 2018 22:05 schreef giorgi-m <notifications@github.com>:
