### ISSUE TITLE
Typescript error in v1.5

### ISSUE THREAD

**Issue by Knacktus** [mweststrate/immer#171]
Just upgraded to version 1.5 in an Angular project. Compilation shows the following errors:

ERROR in node_modules/immer/dist/immer.d.ts(4,3): error TS1131: Property or signature expected.
node_modules/immer/dist/immer.d.ts(4,25): error TS1005: ']' expected.
node_modules/immer/dist/immer.d.ts(4,26): error TS1005: ';' expected.
node_modules/immer/dist/immer.d.ts(4,27): error TS1128: Declaration or statement expected.
node_modules/immer/dist/immer.d.ts(4,40): error TS1005: '(' expected.
node_modules/immer/dist/immer.d.ts(5,1): error TS1128: Declaration or statement expected.
node_modules/immer/dist/immer.d.ts(8,5): error TS1005: ';' expected.
node_modules/immer/dist/immer.d.ts(8,43): error TS1005: '(' expected.
node_modules/immer/dist/immer.d.ts(9,5): error TS1005: ',' expected.
node_modules/immer/dist/immer.d.ts(9,32): error TS1005: '(' expected.
node_modules/immer/dist/immer.d.ts(9,56): error TS1005: '(' expected.
node_modules/immer/dist/immer.d.ts(10,5): error TS1005: ',' expected.
node_modules/immer/dist/immer.d.ts(10,37): error TS1005: '(' expected.
node_modules/immer/dist/immer.d.ts(11,4): error TS1005: ')' expected.
  
Version 1.3.1 works fine.

Cheers,

Jan

**Comment by mweststrate** [comment]
You need at least TS 2.8

Op wo 25 jul. 2018 18:00 schreef Knacktus <notifications@github.com>:

**Comment by Knacktus** [comment]
Meanwhile Angular 6.1 with TS 2.9 was released. All working fine. You just need a little bit of luck :-) ...

**Comment by abidev** [comment]
@mweststrate Thank you for great library... I also faced above issue... But my project is quite big includes couple of teams will not be able upgrade typescript easily... So i went on using UMD

Do you have any other better suggestion in this case ? or is it fine ?

**Comment by mweststrate** [comment]
@abidev you could grab the typings from the 1.4 version of the packages, and use [patch-package](https://www.npmjs.com/package/patch-package) to replace the latest typings with these older ones.

**Comment by abidev** [comment]
@mweststrate Thank you... will try that...
