### ISSUE TITLE
Values sharing isn't preserved

### ISSUE THREAD

**Issue by awto** [mweststrate/immer#174]
* [x] Issue: A reference to a single object points to two different objects after `produce` 
  * Version: 1.5.0
  * Reproduction: https://codesandbox.io/s/j4xrjyvom9
  

  * Expected behavior:  Object properties point to same object after producer
  * Observed behavior: There are two clones
  * [x] Occurs when using Proxies (use `setUseProxies(true)`)
  * [x] Occurs in the ES5 implementation (use `setUseProxies(false)`)

**Comment by awto** [comment]
sorry forgot to save it, this doesn't work in both 1.1.1 and 1.5.0

**Comment by mweststrate** [comment]
Ah this is a completely different test. Immer assumes your data to be a tree indeed, not a graph. Which is typically the case in the contexts where immer is often used. Will make sure to add that more clearly to the readme

**Comment by awto** [comment]
Thanks. Would you be interested to have the thing in Immer? I mean implemented either by holding a global WeakMap or storing a draft object in its original object, it sounds pretty simple to me. I can make a PR (not soon though).

**Comment by mweststrate** [comment]
If it is simple, it is welcome! I thought about it when I wrote this half a
year ago, and then came to the conclusion that it would be quite hairy. But
I don't remember anymore why, so I might have missed the simple solution.

Op do 16 aug. 2018 om 21:56 schreef Vitaliy Akimov <notifications@github.com
