### ISSUE TITLE
patchListener with curried invocation

### ISSUE THREAD

**Issue by travikk** [mweststrate/immer#178]
Hey there,

How can you use patchListener with curried invocation of produce?

**Comment by mweststrate** [comment]
What should the API look like?

Op do 23 aug. 2018 10:23 schreef travikk <notifications@github.com>:

**Comment by travikk** [comment]
So I think this would make sense:

```typescript
export function produce(baseState, producer, patchListener) {
    // prettier-ignore
    if (arguments.length < 1 || arguments.length > 3) throw new Error("produce expects 1 to 3 arguments, got " + arguments.length)

    // curried invocation
    if (typeof baseState === "function") {
        // prettier-ignore
        if (typeof producer === "function") throw new Error("if first argument is a function (curried invocation), the second argument to produce cannot be a function")

        const initialState = producer
        const recipe = baseState

        return function() {
            const args = arguments

            const currentState =
                args[0] === undefined && initialState !== undefined
                    ? initialState
                    : args[0]

            return produce(currentState, draft => {
                args[0] = draft // blegh!
                return recipe.apply(draft, args)
            }, patchListener) // <-- note this
        }
    }

...
}
```

**Comment by mweststrate** [comment]
Ok, but where is that patchListener coming from; how would you use immer in
that case? Can you show how to call a curried producer and grab the patches
(I don't mean technically, I mean API wise)

Op ma 27 aug. 2018 om 08:53 schreef travikk <notifications@github.com>:

**Comment by travikk** [comment]
Yep, so *for me* it would make sense to pass it in when you generate the curried invocation, ie:

```typescript

const myProducer = (draft, index) => {
  draft.idx = index;
};

const myPatchListener = (patches, inversePatches) => {
   ...
};

const curriedProducer = produce(myProducer, null, myPatchListener); // <-- here
[{}, {}, {}].map(curriedProducer);
```

**Comment by mweststrate** [comment]
Ok, but that means that all curried invocations are sharing the same
patchListener, I'm not entirely sure whether that makes sense?

Op ma 27 aug. 2018 om 11:06 schreef travikk <notifications@github.com>:

**Comment by mweststrate** [comment]
> Since they share myProducer, it's not that bad actually.

Well, it means that the producers now have a kind of global state that needs to be 'reset' 

```
const patches = [] 

const myProducer = produce(someFunc, null, p => { patches.push(p) })

myProducer()
// do something with patches
patches.splice(0) // need to reset patches! 

myProducer() // other
// do something with patches. Needs to reset, otherwise sees twice the patches
```

Resetting is easily forgotten, might not happen if an exception is thrown between the producer call and the clear (so one has to use `try / finally`), or might cause concurrency issues if the producer and patches are used in asynchronous processes.

> I guess, additionally you could allow passing patchListener as a first argument to the curriedProducer 

That would cause any current curried invocation to always needing to be called with an undefined first parameter, which is a breaking change and makes one of the most common scenarios ugly (and error prone) to write; `myIncrementProducer(undefined, 3)` instead of `myIncrementProducer(3)`

**Comment by travikk** [comment]
> That would cause any current curried invocation to always needing to be called with an undefined first parameter, which is a breaking change and makes one of the most common scenarios ugly

You could make it optional and do a type check, if the first argument is a function or an object, right?

**Comment by mweststrate** [comment]
The curried invocation could be accepting functions as first argument as
well.

Op ma 27 aug. 2018 om 11:37 schreef travikk <notifications@github.com>:

**Comment by travikk** [comment]
Hm, what will that do? I thought it's only meant to be some sort of state. In that case, it's hard to add it to curriede invocation.

I guess it won't hurt to add it as in the example above?

**Comment by mweststrate** [comment]
@travikk well, you can just curry manually, that is not that hard:

```
const myProducer = (draft, index) => {
  draft.idx = index;
};

const myPatchListener = (patches, inversePatches) => {
   ...
};

const curriedProducer = (state, index) => produce(state, draft => {
 myProducer(draft, index)
}, myPatchListener)

[{}, {}, {}].map(curriedProducer);
```

**Comment by mweststrate** [comment]
Closed, since answered

**Comment by akraines** [comment]
Based on the above answer, I came up with this (for debugging my producers):
```
const logChanges = (patches, inversePatches) => {
    console.log("patches", patches, inversePatches);
};
const loggingProducer = (producer) => (state, action) => produce(state, draft => producer(draft, action), logChanges);
//Usage:
const stateProcessServerData = loggingProducer((draft, {dataObject}) => 
```
