### ISSUE TITLE
Debugging tools?

### ISSUE THREAD

**Issue by jordyvandomselaar** [mweststrate/immer#180]
**Feature Request**

I've been a long time user of Redux, which has amazing debugging tools (Replay state, see actions triggering and what nots)

Is there anything like it for Immer?

**Comment by mweststrate** [comment]
No, Immer is much more low level and not a state managent library. If you use Immer with Redux, you will benefit from the redux devtools, and if you combine it with any other immutable oriented lib you will benefit with the devtools from that lib. Basically you can use any object diffing tool icmw immer. 

But immer has no concepts of actions etc etc.

**Comment by corysimmons** [comment]
immer seems to have a concept of [reducer support](https://github.com/immerjs/immer#reducer-example)? use-immer outright has a `useImmerReducer` function built in: https://github.com/immerjs/use-immer#useimmerreducer

By depending on a tweaked version of https://github.com/troch/reinspect you could potentially seamlessly support Redux DevTools with use-immer, at least. It'd be very similar to easy-peasy at that point, but not force the reducer pattern on the user (component-specific local state could remain `useImmer`), so use-immer would be better imo.

**Comment by johtso** [comment]
@corysimmons do you know if there is a tweaked version of reinspect that supports `useImmerReducer`?

**Comment by corysimmons** [comment]
@johtso No sorry. I think I meant you could fork and tweak your own Reinspect but honestly I would just use easy-peasy.

**Comment by johtso** [comment]
@corysimmons I was initially put off easy-peasy by the fact that it encourages a global store, where I was limiting data to specific components. I gave it another look and found `useLocalStore`.. and everything's working great. Cheers!
