### ISSUE TITLE
Update README.md with patch listener example

### ISSUE THREAD

**Issue by newyork-anthonyng** [mweststrate/immer#182]
I was looking through the documentation and didn't find a way to subscribe to changes to `immer`. It seems like this functionality is available in `immer`, but there aren't examples in the `README.md`.

Let me know if you want me to update it.

Please specify:

(Not filling out _all fields_ of this template will probably result in your issue being closed without further notice. If you are not willing fill it in, why would someone else spent his time fixing it?)

* [X] Feature request: Update README.md
  * [X] I am willing to implement this myself
* [ ] Issue: _______
  * Version: ____
  * _SIMPLE_ Reproduction: ____ (tip: fork this sandbox: https://codesandbox.io/s/vmxmn8omwl)
  * Expected behavior: ___
  * Observed behavior: ___
  * [ ] Occurs when using Proxies (use `setUseProxies(true)`)
  * [ ] Occurs in the ES5 implementation (use `setUseProxies(false)`)

**Comment by mweststrate** [comment]
There is an example in the README here: https://github.com/mweststrate/immer#patches

**Comment by newyork-anthonyng** [comment]
@mweststrate 👍
