### ISSUE TITLE
Readme notes about limitations are confusing.

### ISSUE THREAD

**Issue by Izhaki** [mweststrate/immer#185]
* [X] Issue: Documentation
  * Version: Master
  
[README > Limitations / Pitfalls](https://github.com/mweststrate/immer/blob/0a80c2c108a41b810028a539a8699dea66000d77/readme.md#limitations--pitfalls)

This is how I read it first time until I decided this makes no sense:

> Immer only supports plain objects and arrays. 

My thoughts: So no support for strings and integers?
Assumed meaning: It does not support Map and Set (clear in the 1.5.0 README).

> For arrays it is assumed only numeric properties (and length) are used.

My thoughts: So arrays cannot contain strings?
Assumed meaning: No idea.

**Comment by datenreisender** [comment]
In the same section the 

> 4. Class instances are not, and will not be supported. Read here more on why that would be a [confusing, conceptual mismatch]

confuses me. It looks like `here` should be a link and `[confusing, conceptual mismatch]` looks like it is a draft where the author still wanted to decide, what to actually write.

**Comment by mweststrate** [comment]
Clarified the readme on both points, feel free PR further changes if anything is still unclear
