### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by HiMrHu** [mweststrate/immer#187]
Hello, I have a question. I found the following code in your code

```javascript

    {
        if (typeof producer !== "function") throw new Error("if first argument is not a function, the second argument to produce should be a function")
    }


```
What is the purpose and significance of {} here？
Looking forward to your reply.

**Comment by mweststrate** [comment]
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block

I doesn't serve any purpose any in this code base and could be removed semantically, but in this case I abused it to apply a single `// prettier-ignore` to multiple statements at once.
