### ISSUE TITLE
Usage with eslint no-param-reassign

### ISSUE THREAD

**Issue by brummelte** [mweststrate/immer#189]
I don't want to disable the eslint rule "no-param-reassign" globally, because it prevents errors.

So this seems to be the best way to use immer with that rule enabled:
```javascript
const nextState = produce(baseState, (draftState) => {
    /* eslint-disable no-param-reassign */
    draftState.push({ todo: "Tweet about it" });
    /* eslint-enable no-param-reassign */
});
```

There is a way to specify "ignorePropertyModificationsFor" for that eslint rule (https://eslint.org/docs/rules/no-param-reassign). So draftState could be ignored. But that would only exclude that name.

Is there a better way without disabling that rule?

**Comment by mweststrate** [comment]
@brummelte I don't think your example is a param reassign and the rule shouldn't trigger on it

**Comment by brummelte** [comment]
You are correct, I just copied it from your example. But the question stays the same:

```javascript
const nextState = produce(baseState, (draftState) => {
    /* eslint-disable no-param-reassign */
    draftState.test = "New value";
    /* eslint-enable no-param-reassign */
});
```

**Comment by brummelte** [comment]
It is with the option `{ "props": false }`.

**Comment by mweststrate** [comment]
Wow that's an insane rule disabling half the language. But not going to
argue it,  that is too tiring. you might try to set option
ignorePropertyModificationsFor: "draft".

Otherwise; drop either that rule or immer.


Op vr 14 sep. 2018 20:27 schreef Jan Brummelte <notifications@github.com>:

**Comment by mweststrate** [comment]
For future readers: did that option solve the issue?

Op vr 14 sep. 2018 om 21:13 schreef Jan Brummelte <notifications@github.com

**Comment by davalapar** [comment]
Won't this work? 

```
const nextState = produce(baseState, ({ push }) => {
    push({ todo: "Tweet about it" });
});
```

**Comment by brummelte** [comment]
> For future readers: did that option solve the issue?
The issue was, that that is not the perfect solution. But yes, that setting would work.

**Comment by mweststrate** [comment]
Ok, to summarize:

1. `no-param-reassign` rule makes perfect sense, I actually strongly recommend it, because `draft = X` assignments are really a no-op
2. `props: true` option though kinda defeats the purpose of immer, and should be kept to `false` (the default), or an exception could be made by setting `ignorePropertyModificationsFor: "draft"`

**Comment by jaimefps** [comment]
Just to make it quicker for ya'll, 
if you are extending `airbnb`, 
just do the following in your `eslint.rc` file:

```
module.exports = {
  extends: [
    'airbnb', // this means you have "props" = "true" by default
  ],
  rules: {
    'no-param-reassign': ['error', { props: true, ignorePropertyModificationsFor: ['draft'] }],
  },
};
```

**Comment by nurbek-ab** [comment]
Also in case you have multiple producers in the same scope, like this:
```
  markAsSubmitted = isLoading => {
    this.setState(produce(draft => {
      draft.loading = isLoading;
      draft.secondLevel = draft.secondLevel.map(produce(sketch => {
        sketch.submitted = true;
        sketch.thirdLevel = sketch.thirdLevel.map(produce(outline => {
          outline.submitted = true;
        }));
      }));
    }));
  };
```
This rule would work:
```
    "no-param-reassign": ["error", {
      "props": true,
      "ignorePropertyModificationsFor": ["draft", "sketch", "outline"]
    }],
```

**Comment by SpotHimesh** [comment]
For people coming from future google searches, extending on @jaimefps [comment](https://github.com/immerjs/immer/issues/189#issuecomment-506396244) above

To enable more semantic variable naming as well as avoiding problem in case of multiple producers in the same scope, we can do

```JS
module.exports = {
  extends: [
    'airbnb', // this means you have "props" = "true" by default
  ],
  rules: {
    'no-param-reassign': ['error', { props: true, ignorePropertyModificationsForRegex: ["^draft"] }],
  },
};
```

This should make it work for `draft`, `draftPost`, `draftState`

**Comment by zedelashvililevani** [comment]
Another trick that works:

```
const nextState = produce(baseState, (draft) => {
    const tempDraft = draft;
    tempDraft .test = "New value";
});
```

**Comment by ljharb** [comment]
@crismon96 in some JS engines, reassigning to a named argument heavily deoptimizes the function. Always make a new variable name instead.

**Comment by daliborfilus** [comment]
That rule triggered for me in immer (that's how I landed on this issue), but also on code like this:

```js
export function groupBy(data, fnc) {
  return data.reduce((acc, curr) => {
    const res = fnc(curr);
    if (!acc[res]) acc[res] = [curr];
    else acc[res].push(curr);
    return acc;
  }, {});
}
```

 75:20  error  Assignment to property of function parameter 'acc'  no-param-reassign

So now I can't even use reduce anymore? This rule (with `props: true`) is just stupid.
I think I'll just set props to false.
