### ISSUE TITLE
Performance with Redux combineReducers

### ISSUE THREAD

**Issue by dangerousdan** [mweststrate/immer#196]
This isn't a feature request. Just a query regarding performance & best practice.

Many people using Redux will have multiple reducers, and combine them with combineReducers. This means that a lot of the time the reducer will not fire any action at all (because the action exists on another reducer).

The `produce` method creates a proxy, right? Is this an expensive operation to do, when the reducer isn't modifying the state at all?

Ie: Rather than this (switch inside of produce):
```javascript
const reducer = (state = defaultState, action) =>
  produce(state, draft => {
    switch (action.type) {
      case 'ADD':
        draft.push(action.payload)
        return draft
    }
  })
```

Would it not be better to do this (produce inside of switch):

```javascript
const reducer = (state = defaultState, action) => {
  switch (action.type) {
    case 'ADD':
      return produce(state, draft => {
        draft.push(action.payload)
        return draft
      })
    default:
      return state
  }
}
```

Then if no action is triggered, no proxy is used.

Or are there any performance benefits to always returning a proxy that I am missing?

[Example in CodeSandbox](https://codesandbox.io/s/1oxy84q1o7)

**Comment by mweststrate** [comment]
Creating proxies is cheap, especially in browsers that support proxies.

Like typically with these kind of things; theoretically you are right that the second approach is expected to be faster. In practice though, it might very well not matter at all, unless you are running  your reducers an insane amount of times per second, but then your bottlenecks will probably be somewhere else.

In other words, personally I wouldn't optimize this, until I _know_ it cause a perf bottleneck. Until you can proof from numbers that it matters, go for code clarity and DX.

**Comment by salvoravida** [comment]
@dangerousdan maybe this could help?
https://github.com/salvoravida/immer-combine-reducers
