### ISSUE TITLE
Upgraded to 1.7.2, typescript typedefs changes failing build

### ISSUE THREAD

**Issue by scriby** [mweststrate/immer#205]
* [x] Issue: Upgraded to 1.7.2, typescript typedefs changes failing build
  * Version: 1.7.2
  * _SIMPLE_ Reproduction: 

Attempting to build Typescript code that looks like this doesn't work anymore:

```
import {produce, Draft} from 'immer';

const producer = produce((draft: Draft<State>, action: Action) => {
  draft.xyz = action.xyz;
});
```

This code built previously under 1.2.1, but does not build under 1.7.2 (only change is I changed `State` to `Draft<State>`). Typescript is complaining that "void" is not assignable to type DraftObject<State>.

I think it's supposed to be matching this type def:

```
// 1 additional argument of type A
<S = any, A = any>(recipe: (this: Draft<S>, draftState: Draft<S>, a: A) => void|S): 
    (currentState: S, a: A) => S
```

I think the issue is that the typedef declares that the recipe function will return an "S", but that's going to be difficult because it receives a `Draft<S>`. Tweaking the type def locally and having recipe return `void|Draft<S>` fixes the issue for me.

  * Expected behavior: It builds
  * Observed behavior: It doesn't build
  * [x] Occurs when using Proxies (use `setUseProxies(true)`)
  * [x] Occurs in the ES5 implementation (use `setUseProxies(false)`)

**Comment by scriby** [comment]
As an update to this, the old style type defs work better for my codebase:

```
<S = any>(
      currentState: S, recipe: (this: S, draftState: S) => void|S,
      listener?: PatchListener): S

// 1 additional argument of type A
<S = any, A = any>(recipe: (this:S, draftState:S, a: A) => void|S): 
    (currentState: S, a: A) => S
```
The code doesn't really need to use the Draft state, so it's easier just to leave it like this. Not sure if you still consider these "valid" or not, but they still look ok to me.

**Comment by mweststrate** [comment]
@scriby can you demonstrate this in a sandbox, because if I read your example correctly, your recipe returns `void`, not `S`, so that should work out fine?

**Comment by aleclarson** [comment]
@scriby What version of TypeScript are you using?

Repro: https://codesandbox.io/s/x7y885rlww (I don't know which TS version is in CodeSandbox)

My fix passes [here](https://goo.gl/t28pcV), but I don't know which TS version is used there.

It also passes locally using `typescript v3.1.0`.

**Comment by aleclarson** [comment]
The problem was that the generic `S` was being referred from the return value of the recipe function.

**Comment by scriby** [comment]
Since filing this issue I've noticed the TS version at work doesn't (or doesn't always?) treat void and undefined as the same type. We're on a little older version, so that might be the cause. I'll go ahead and close for now until we get on a more recent version.
