### ISSUE TITLE
Feature request: ability to make state changes in patchListener

### ISSUE THREAD

**Issue by asvetliakov** [mweststrate/immer#218]
* [x] Feature request: Ability to make state changes based on produced ```patches```
  * [ ] I am willing to implement this myself

It would be great if there will be possible to make final changes to the state tree based on patches produced by producer. One great example is the implementing versioning of the objects in the state. Something like ```patchListener(patches, inversePatches, result)``` would work (also calling before freezing of the final state). Thanks

**Comment by aleclarson** [comment]
What is `result` in your example? The immutable object produced by the given `patches` array?

> make final changes to the state tree based on patches produced by producer

What kind of changes do you have in mind?

**Comment by asvetliakov** [comment]
@aleclarson 
>What is result in your example? The immutable object produced by the given patches array?
Yes, correct, after producing a fresh copies of changed structures, but before final freezing in dev mode (although freezing is not the problem since it can be disabled, but nice to have).

>What kind of changes do you have in mind?
Versioning. Storing previous values in app offline mode. Assigning custom cache keys for implementing custom update-checking strategy. Something like it:

```js
incrVersion = a => a && typeof a === "object" && a[VERSION]++;

produce(st, dr => {
   dr.a.b = true;
}, (patches, res) => {
   patches.forEach(pa => p.path.reduce((curr, p) => incrVersion(curr); return curr[p], res));
}
```

**Comment by aleclarson** [comment]
Oh, you want to pass it into `produce`. I thought you wanted to hook into Immer to call the same function for every object mutated by Immer.

This should help you:
```js
import {produce as immerProduce} from 'immer'
const patchedProduce = (listener) => (state, recipe) => {
  let patches
  let result = immerProduce(state, recipe, $1 => (patches = $1))
  return listener(patches, result)
}

// Save this for re-use
const produce = patchedProduce((patches, result) => {
  /* Do your thing */
  return result
})

// Call it elsewhere
produce(state, recipe)
```

I'd say this probably belongs in userland as its own package.

**Comment by asvetliakov** [comment]
Forgot you can curry and stole arguments. Thanks, this works.
