### ISSUE TITLE
TypeScript compiling error

### ISSUE THREAD

**Issue by mmakrzem** [mweststrate/immer#223]
Please specify:

(Not filling out _all fields_ of this template will probably result in your issue being closed without further notice. If you are not willing fill it in, why would someone else spent his time fixing it?)

* [ ] Feature request: ______
  * [ ] I am willing to implement this myself
* [ X] Issue: _______
  * Version: 

immer: v1.7.2
TypeScript: v3.1.3

  * _SIMPLE_ Reproduction: 
 I have some TypeScript code that is something like this:

https://codesandbox.io/s/771oop1rj

This should work I believe however I get the following Typescript error on the line 20.  (Note, this error doesn't appear in the codesandbox.io code.  I don't know why)

The error that I see is:

```javascript
Cannot invoke an expression whose type lacks a call signature. Type 'DraftObject<{ <S extends IButtonResource>(predicate: (this: void, value: IButtonResource, index: ...' has no compatible call signatures.
```

To get around the problem, if I cast draft this way:

```javascript
return ( draft as Types.IButtonResource[] ).find(resource => resource.key === "b");
```

then the TypeScript compiler doesn't complain.

**Comment by aleclarson** [comment]
I assume you meant:
```ts
import { Draft as DraftObject, produce } from "immer";
```

Please fix the formatting of your post. 🍰 

And fork [this sandbox](https://codesandbox.io/s/react-ts) and paste your reproduction in there. :)

**Comment by aleclarson** [comment]
Thanks for fixing the formatting!

You shouldn't be using `DraftObject` directly, especially not with an array type. Use `Draft` instead.
