### ISSUE TITLE
TypeError: Cannot convert undefined or null to object only on production

### ISSUE THREAD

**Issue by pioz** [mweststrate/immer#224]
Please specify:

(Not filling out _all fields_ of this template will probably result in your issue being closed without further notice. If you are not willing fill it in, why would someone else spent his time fixing it?)

* [ ] Feature request: ______
  * [ ] I am willing to implement this myself
* [*] Issue: 
I've a React Component with this state and a function to update the state like this:
```
this.state = { products: [], currentCart: { subcarts: [] } }
setCurrentCart = (currentCart) => {
  this.setState(
    produce(draft => {
      draft.currentCart = currentCart
      for (let i = 0; i < currentCart.subcarts.length; i++) {
        for (let j = 0; j < this.state.products.length; j++) {
          if (this.state.products[j].user_id === currentCart.subcarts[i].seller_id) {
            draft.products[j].seller_in_cart = true
          }
        }
      }
    })
  )
}
```
In my development environment all work as expected, but in production I get:
```
raven.js:58 TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
   ...
at Object.enqueueSetState (application-fbddb90bf6b96e79b7ff90890c536b805bce130b90d738490b11a2dc47265c3a.js:181943)
    at o.n.setState (application-fbddb90bf6b96e79b7ff90890c536b805bce130b90d738490b11a2dc47265c3a.js:152045)
    at Object.s.setCurrentCart (application-fbddb90bf6b96e79b7ff90890c536b805bce130b90d738490b11a2dc47265c3a.js:75133)
```
Any idea? If I `setUseProxies(false)` this works also in production.

  * Version: 1.7.2
  * [ *] Occurs when using Proxies (use `setUseProxies(true)`)
  * [ ] Occurs in the ES5 implementation (use `setUseProxies(false)`)

**Comment by aleclarson** [comment]
Please [fork this](https://codesandbox.io/s/new) and copy as little of your code as possible to reproduce the bug, if you have the time. 👍

**Comment by pioz** [comment]
I can't reproduce on codesandbox.io... But I don't know if the code in codesandbox.io is running in node production environment.

**Comment by mweststrate** [comment]
@pioz, since your stack trace contains `setState`, it lookls like that the producer is already finished and your exception is not coming from the `produce`, but from the `setState`, meaning that there is some assumption on the internal data structure that is not matched. So it looks unrelated to immer to me, but if it is, please provide a reproduction as @aleclarson indicated.

**Comment by pioz** [comment]
With a fresh react app with `create-react-app` all works fine.
But in my project I use browserify with the command: `browserifyinc -t [ babelify --presets [@babel/env @babel/react] --plugins [@babel/plugin-proposal-class-properties] ]`. May be this can cause the issue?

**Comment by pioz** [comment]
Here a Rails repo to reproduce the issue: https://github.com/pioz/immer-debug-issues-224 
The instructions in the `README.md`

**Comment by mweststrate** [comment]
Please isolate the problem first, it shouldn't need to take a Rails project
to reproduce this issue if it is on the immer side of things

Op ma 22 okt. 2018 om 14:02 schreef Enrico <notifications@github.com>:

**Comment by pioz** [comment]
I know, but I have no idea how to reproduce the issue in a simple react app. Sorry. Anyway the problem is isolated in the fresh rails app that I have shared...

> Please isolate the problem first, it shouldn't need to take a Rails project to reproduce this issue if it is on the immer side of things Op ma 22 okt. 2018 om 14:02 schreef Enrico <notifications@github.com>:
> […](#)

**Comment by pioz** [comment]
@mweststrate if you want I can prepare a docker container... can this help you?

**Comment by mweststrate** [comment]
@pioz so far it feels as a general JavaScript error, totally unrelated to immer. (The stacktrace is from `raven.js`, which is the backing library of sentry.io, are you using that in your production builds only for example)? Did you already try to break the debugger on that exception and check what variable is unexpectedly `undefined` or `null`?

Also, try to break out your set state call, like this, and see if you got a normal object back. 

```javascript
this.state = { products: [], currentCart: { subcarts: [] } }
setCurrentCart = (currentCart) => {
  this.setState(prevState => {
    const nextState = produce(draft => { //
      draft.currentCart = currentCart
      for (let i = 0; i < currentCart.subcarts.length; i++) {
        for (let j = 0; j < this.state.products.length; j++) {
          if (this.state.products[j].user_id === currentCart.subcarts[i].seller_id) {
            draft.products[j].seller_in_cart = true
          }
        }
      }
    })(prevState) //
    console.log(nextState) // If you get here, and the state looks sane, immer / this producer is not the problem
    return nextState // you can even grab the state printed above, and put it literally in your state updater, to test your production build
  )
}
```

**Comment by pioz** [comment]
I've just try to debug in this way and the `console.log` at the end of the `setCurrentCart` function never get reached. The error is triggered on `draft.products[j]`. Im pretty sure about this.

**Comment by aleclarson** [comment]
I tried to reproduce the above snippet in CodeSandbox. [See here](https://codesandbox.io/s/k98r8x50k5)

Just press the Foo button and open the console.

**Comment by mweststrate** [comment]
Ok, in that case can you grab the `prevState`? Together with the producer
that should reproduce your bug.

Op di 23 okt. 2018 om 15:52 schreef Enrico <notifications@github.com>:

**Comment by mweststrate** [comment]
Which browser? Seems to work fine for me

Op di 23 okt. 2018 om 16:25 schreef Alec Larson <notifications@github.com>:

**Comment by aleclarson** [comment]
@mweststrate Yes, it works fine for me, too. Need a better repro.

**Comment by mweststrate** [comment]
@pioz p.s note that you should probably not use `this.state` in your producer, but `draft` to read the current state, state updates are asynchronous in React, so it means that you might be looking at an old or inconsistent state. For example two setState calls might run quickly after each other before a rendering happens, that means that `this.state` still contains state version 0 when the second setState is triggered, while draft contains state version 1 (the one produced by the previous setState)

**Comment by pioz** [comment]
I've found a solution: Rails Uglifier (https://github.com/lautis/uglifier) causes the issue, BUT if you pass the option `harmony: true` to Uglifier, all works good also in production with Rails!

**Comment by rymohr** [comment]
We just got bit by this also. Worked fine in development but broke in production when uglifier was enabled.

```
config.assets.js_compressor = :uglifier
```

It could be totally unrelated, but I think it's worth noting that we didn't have this issue until a recent upgrade to webpack 4 / babel 7.

**Comment by rymohr** [comment]
Sounds like the babel upgrade is likely the culprit:

![image](https://user-images.githubusercontent.com/730211/49173948-2bbe6580-f2e9-11e8-922e-1603ffb5e0fd.png)

https://babeljs.io/docs/en/babel-preset-env#forcealltransforms
