### ISSUE TITLE
Use es5 implementation in browsers where Proxy is supported but Reflect is not

### ISSUE THREAD

**Issue by vikas-parashar** [mweststrate/immer#226]
* [ ] Feature request: ______
  * [x] I am willing to implement this myself
* [x] Issue: Browsers in which Proxy is not supported ES5 implementation is used but in `firefox 41` `Proxy` is supported but `Reflect` is not so it default implementation with Proxies is used which throws error `Reflect is not defined`
  * Version: 1.7.1
  * _SIMPLE_ Reproduction: codesandbox itself doesn't work in `firefox 41` but check of support of [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#Browser_compatibility) and [Reflect](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect#Browser_compatibility) confirms the issue.
  * Expected behavior: ___
  * Observed behavior: ___
  * [x] Occurs when using Proxies (use `setUseProxies(true)`)
  * [ ] Occurs in the ES5 implementation (use `setUseProxies(false)`)

Fix: Check for support for both Reflect and Proxy to use ES5 implementation.

**Comment by mweststrate** [comment]
Looks like a bug indeed!
