### ISSUE TITLE
Nested drafts inside new objects

### ISSUE THREAD

**Issue by aleclarson** [mweststrate/immer#230]
This scenario seems like it's handled wrong by Immer.

Imagine creating a new object in your producer and adding a draft object as a property.

If your new object is ever frozen before your producer returns, you end up with the draft object never being replaced with the original. And worse, you now have a revoked proxy instead of the object you wanted.

I think Immer should always clone frozen objects when any of their properties is a draft object.

Here's a failing test case:

```js
it("ensures new objects never contain a draft", () => {
    const base = {a: {}}
    const next = produce(base, draft => {
        return {
            foo: {a: draft.a},
            bar: Object.freeze({a: draft.a})
        }
    })

    // Mutable object
    expect(original(next.foo.a)).toBeUndefined()
    expect(next.foo.a).toBe(base.a)

    // Frozen object
    expect(original(next.bar.a)).toBeUndefined()
    expect(next.bar.a).toBe(base.a)
})
```

**Comment by mweststrate** [comment]
If you are deliberately force freezing something (why would you), that is just a sign that you want to have literally that thing. So if you really want to forcefully return a draft, then you'll have it, despite it begin useless. I think this use case is no different then: 

```javascript
produce(base, draft =>({
   foo: {a: draft.a},
   bar() { return draft }
}).bar().a // throws, you leaked a draft
```

The goal is to behave good if you have good intentions. Freezing a draft looks to me like deliberately trying to counter the abstraction provided (namely, having mutable, not frozen drafts), and it that case you are on your own :)

**Comment by aleclarson** [comment]
There's also a chance that a user wants to `deepFreeze` some new object that happens to contain a draft.

**Comment by aleclarson** [comment]
What if we provide a `freeze` function that prevents draft leaks?

**Comment by aleclarson** [comment]
*Note:* To email users, I made edits to past comments.

@mweststrate So you're asking _every producer_ to use `original` before passing a draft object to _any function_ whose return value is ever (1) _frozen_ and (2) added to the draft / replaces the draft. Is this an accurate depiction?

**Comment by aleclarson** [comment]
ping @mweststrate

**Comment by mweststrate** [comment]
I think that introducing a freeze utility + the fact that immer freezes itself will be highly confusing. I would rather propose a more aggressive setting like `setAutoFreeze("everything")`, which is more expensive, but always recursively freezes stuff

I didn't entirely get the last comment, about `original` usage. But still the pattern of freezing something that contains drafts doesn't make any sense to me. That is exactly not what you want conceptually, freeze something that has a draft, because it means that it can never be "undrafted", except by being cloned, but if you clone, what was the point of the freezing in the first place? Freeze to me means conceptually: "this is exactly, literally what I want and want to stay as it is now".

**Comment by aleclarson** [comment]
> I think that introducing a freeze utility + the fact that immer freezes itself will be highly confusing.

Idk, it's not hard to learn that draft mutations in `produce` create **shallow-frozen** copies, and any objects **created in the producer** must be frozen manually (using the `freeze` utility to avoid leaking drafts and to take advantage of `setAutoFreeze`).

If that really confuses people, they can use `setAutoFreeze('deep')` or avoid **deeply**-freezing objects that _may_ contain a draft (which is probably rare).

Honestly, I think we could both add `setAutoFreeze('deep')` and export an updated `freeze()` that checks for drafts before freezing. :)

**Comment by mweststrate** [comment]
I think #254 could introduces the possibility of a deep freeze. Still don't see much merit in it, as there are packages out there that take care of deep freezing in general, so just use using something like `nextState = deepFreeze(producer(state, fn))` should be fine imho, or it could be take care of by the hooks proposed earlier. 

Freezing itself is not the goal of this package, but just a debug utility, and introduces a new area of possible problems (where different people might need different answers to. Use full recursion? Include symbolic members, enumerables, prototypes, functions, etc etc)

**Comment by aleclarson** [comment]
Closing this until it becomes an issue for me.
