### ISSUE TITLE
not an issue : immer does not work with native js types right?

### ISSUE THREAD

**Issue by brucou** [mweststrate/immer#235]
As under the hood, immer uses proxies, I was wondering if it was working with native js types (say number).

**Comment by aleclarson** [comment]
Immer only proxies plain objects and arrays.

The following snippet is where that logic lives:

https://github.com/mweststrate/immer/blob/004bb7f4471f3dae3c93ba5f06608de3be06e4e3/src/immer.js#L52-L68

**Comment by aleclarson** [comment]
Here are the unit tests for using `produce` with a primitive base state.

https://github.com/mweststrate/immer/blob/004bb7f4471f3dae3c93ba5f06608de3be06e4e3/__tests__/base.js#L1149-L1171

**Comment by aleclarson** [comment]
*Side note:* There are some minor bugs when calling `produce` with a base state of certain types. #233

**Comment by brucou** [comment]
That 's the best answer I ever had in a long time. Thanks
