### ISSUE TITLE
setState: partial state vs full state update

### ISSUE THREAD

**Issue by mgenware** [mweststrate/immer#242]
Thanks for this amazing library. I got one question when reading through the docs, the [React setState example](https://github.com/mweststrate/immer#reactsetstate-example) section says:
```js
/**
 * Classic React.setState with a deep merge
 */
onBirthDayClick1 = () => {
    this.setState(prevState => ({
        user: {
            ...prevState.user,
            age: prevState.user.age + 1
        }
    }))
}

/**
 * ...But, since setState accepts functions,
 * we can just create a curried producer and further simplify!
 */
onBirthDayClick2 = () => {
    this.setState(
        produce(draft => {
            draft.user.age += 1
        })
    )
}
```

I think there is one subtle difference here, the classic example always returns an object with one property, i.e. `user`. But the producer example would return all state properties as demonstrated below:
```js
const baseState = {
  a: 1, b: 2, user: { age: 18 },
};
const cb = produce(draftState => {
  draftState.user.age += 1;
});

console.log(cb(baseState));
```

It prints
```
{ a: 1, b: 2, user: { age: 19 } }
```

So it seems that every time i call `produce` with `React.setState`, i got a full state update, and this is more of a react thing, but i failed to find any useful info on this since everyone uses partial update on `setState`. Wondering if there's any downside on full state update, thanks in advance!

**Comment by aleclarson** [comment]
This question is specific to React, so I would try asking over there, if @mweststrate doesn't know.

**Comment by mweststrate** [comment]
I think it doesn't matter, a partial `setState` is just merged into the current full state, and depending on your local optimizations from that point on shallow comparison might happen. So as long as you use curried producers the behavior will be the same as far as I can see.
