### ISSUE TITLE
Draft type clobbers nested object types in typescript 3.1.3

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [mweststrate/immer#243]
* [X] Issue:
  * Version: 1.7.4
  * _SIMPLE_ Reproduction: [typescript playground](https://www.typescriptlang.org/play/#src=%2F%2F%20Copied%20directly%20from%20immer.d.ts%0D%0A%2F**%20Object%20types%20that%20should%20never%20be%20mapped%20*%2F%0D%0Atype%20AtomicObject%20%3D%0D%0A%20%20%20%20%7C%20Function%0D%0A%20%20%20%20%7C%20Map%3Cany%2C%20any%3E%0D%0A%20%20%20%20%7C%20WeakMap%3Cany%2C%20any%3E%0D%0A%20%20%20%20%7C%20Set%3Cany%3E%0D%0A%20%20%20%20%7C%20WeakSet%3Cany%3E%0D%0A%20%20%20%20%7C%20Promise%3Cany%3E%0D%0A%20%20%20%20%7C%20Date%0D%0A%20%20%20%20%7C%20RegExp%0D%0A%20%20%20%20%7C%20Boolean%0D%0A%20%20%20%20%7C%20Number%0D%0A%20%20%20%20%7C%20String%0D%0A%0D%0A%2F**%20Use%20type%20inference%20to%20know%20when%20an%20array%20is%20finite%20*%2F%0D%0Atype%20IsFinite%3CT%20extends%20any%5B%5D%3E%20%3D%20T%20extends%20never%5B%5D%0D%0A%20%20%20%20%3F%20true%0D%0A%20%20%20%20%3A%20T%20extends%20ReadonlyArray%3Cinfer%20U%3E%20%3F%20(U%5B%5D%20extends%20T%20%3F%20false%20%3A%20true)%20%3A%20true%0D%0A%0D%0Aexport%20type%20DraftObject%3CT%3E%20%3D%20T%20extends%20object%0D%0A%20%20%20%20%3F%20T%20extends%20AtomicObject%20%3F%20T%20%3A%20%7B-readonly%20%5BP%20in%20keyof%20T%5D%3A%20Draft%3CT%5BP%5D%3E%7D%0D%0A%20%20%20%20%3A%20T%0D%0A%0D%0Aexport%20type%20DraftArray%3CT%3E%20%3D%20Array%3C%0D%0A%20%20%20%20T%20extends%20ReadonlyArray%3Cany%3E%0D%0A%20%20%20%20%20%20%20%20%3F%20%7B%5BP%20in%20keyof%20T%5D%3A%20Draft%3CT%3E%7D%5Bkeyof%20T%5D%0D%0A%20%20%20%20%20%20%20%20%3A%20DraftObject%3CT%3E%0D%0A%3E%0D%0A%0D%0Aexport%20type%20DraftTuple%3CT%20extends%20any%5B%5D%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%20extends%20T%5Bnumber%5D%20%3F%20Draft%3CT%5BP%5D%3E%20%3A%20never%0D%0A%7D%0D%0A%0D%0Aexport%20type%20Draft%3CT%3E%20%3D%20T%20extends%20any%5B%5D%0D%0A%20%20%20%20%3F%20IsFinite%3CT%3E%20extends%20true%20%3F%20DraftTuple%3CT%3E%20%3A%20DraftArray%3CT%5Bnumber%5D%3E%0D%0A%20%20%20%20%3A%20T%20extends%20ReadonlyArray%3Cany%3E%0D%0A%20%20%20%20%20%20%20%20%3F%20DraftArray%3CT%5Bnumber%5D%3E%0D%0A%20%20%20%20%3A%20T%20extends%20object%20%3F%20DraftObject%3CT%3E%20%3A%20T%0D%0A%2F%2F%20end%20copy%0D%0A%0D%0Ainterface%20State%20%7B%20user%3A%20%7B%20x%3A%20string%20%7D%20%7D%0D%0Atype%20T0%20%3D%20Draft%3CState%3E%0D%0A)
```ts
import { Draft } from "immer";

interface State {
  x: { y: string };
}

type T0 = Draft<State> // $ExpectType State
```
  * Expected behavior: type T0 has type identical to state
  * Observed behavior: type T0 has type { x: any }

The issue stems from the mutual recursion between DraftObject<T> and Draft<T>.
It is reproducible with ([typescript playground](https://www.typescriptlang.org/play/#src=type%20DraftObject%3CT%3E%20%3D%20T%20extends%20object%20%3F%20%7B-readonly%20%5BP%20in%20keyof%20T%5D%3A%20Draft%3CT%5BP%5D%3E%7D%20%3A%20T%0D%0Atype%20Draft%3CT%3E%20%3D%20T%20extends%20object%20%3F%20DraftObject%3CT%3E%20%3A%20T%0D%0Atype%20T0%20%3D%20Draft%3C%7B%20x%3A%20%7B%20y%3A%20string%20%7D%20%7D%3E)):
```ts
type DraftObject<T> = T extends object ? {-readonly [P in keyof T]: Draft<T[P]>} : T
type Draft<T> = T extends object ? DraftObject<T> : T
type T0 = Draft<{ x: { y: string } }>
```
where Draft is identical to Draft from immer, but with cases for arrays and tuples removed

**Comment by WhiteAbeLincoln** [comment]
If the conditional types are removed from DraftObject it appears to work ([typescript playground](https://www.typescriptlang.org/play/#src=type%20DraftObject%3CT%3E%20%3D%20%7B-readonly%20%5BP%20in%20keyof%20T%5D%3A%20Draft%3CT%5BP%5D%3E%7D%0D%0Atype%20Draft%3CT%3E%20%3D%20T%20extends%20object%20%3F%20DraftObject%3CT%3E%20%3A%20T%0D%0Atype%20T0%20%3D%20Draft%3C%7B%20x%3A%20%7B%20y%3A%20string%20%7D%20%7D%3E)):
```ts
type DraftObject<T> = {-readonly [P in keyof T]: Draft<T[P]>}
type Draft<T> = T extends object ? DraftObject<T> : T
type T0 = Draft<{ x: { y: string } }>
```

**Comment by aleclarson** [comment]
Whoops! Didn't think to test interfaces. Bug confirmed! 👍 

Looking into a fix...

**Comment by WhiteAbeLincoln** [comment]
If we extract the mapped type into its own type, then the issue doesn't occur ([typescript playground](https://www.typescriptlang.org/play/#src=type%20AtomicObject%20%3D%0D%0A%20%20%7C%20Function%0D%0A%20%20%7C%20Map%3Cany%2C%20any%3E%0D%0A%20%20%7C%20WeakMap%3Cany%2C%20any%3E%0D%0A%20%20%7C%20Set%3Cany%3E%0D%0A%20%20%7C%20WeakSet%3Cany%3E%0D%0A%20%20%7C%20Promise%3Cany%3E%0D%0A%20%20%7C%20Date%0D%0A%20%20%7C%20RegExp%0D%0A%20%20%7C%20Boolean%0D%0A%20%20%7C%20Number%0D%0A%20%20%7C%20String%0D%0A%0D%0Atype%20IsFinite%3CT%20extends%20any%5B%5D%3E%20%3D%20T%20extends%20never%5B%5D%0D%0A%20%20%3F%20true%0D%0A%20%20%3A%20T%20extends%20ReadonlyArray%3Cinfer%20U%3E%20%3F%20(U%5B%5D%20extends%20T%20%3F%20false%20%3A%20true)%20%3A%20true%0D%0A%0D%0A%2F%2F%20we%20extracted%20the%20mapped%20type%20into%20its%20own%20name%0D%0Aexport%20type%20DraftObjectReal%3CT%3E%20%3D%20%7B%20-readonly%20%5BP%20in%20keyof%20T%5D%3A%20Draft%3CT%5BP%5D%3E%20%7D%0D%0Aexport%20type%20DraftObject%3CT%3E%20%3D%20T%20extends%20object%0D%0A%20%20%3F%20T%20extends%20AtomicObject%20%3F%20T%20%3A%20DraftObjectReal%3CT%3E%0D%0A%20%20%3A%20T%0D%0A%0D%0Aexport%20type%20DraftArray%3CT%3E%20%3D%20Array%3C%0D%0A%20%20T%20extends%20ReadonlyArray%3Cany%3E%0D%0A%20%20%20%20%3F%20%7B%20%5BP%20in%20keyof%20T%5D%3A%20Draft%3CT%3E%20%7D%5Bkeyof%20T%5D%0D%0A%20%20%20%20%3A%20DraftObject%3CT%3E%0D%0A%3E%0D%0A%0D%0Aexport%20type%20DraftTuple%3CT%20extends%20any%5B%5D%3E%20%3D%20%7B%0D%0A%20%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%20extends%20T%5Bnumber%5D%20%3F%20Draft%3CT%5BP%5D%3E%20%3A%20never%0D%0A%7D%0D%0A%0D%0Aexport%20type%20Draft%3CT%3E%20%3D%20T%20extends%20any%5B%5D%0D%0A%20%20%3F%20IsFinite%3CT%3E%20extends%20true%20%3F%20DraftTuple%3CT%3E%20%3A%20DraftArray%3CT%5Bnumber%5D%3E%0D%0A%20%20%3A%20T%20extends%20ReadonlyArray%3Cany%3E%0D%0A%20%20%20%20%3F%20DraftArray%3CT%5Bnumber%5D%3E%0D%0A%20%20%20%20%3A%20T%20extends%20object%20%3F%20DraftObject%3CT%3E%20%3A%20T%0D%0A%0D%0Atype%20T0%20%3D%20Draft%3C%7B%20x%3A%20%7B%20y%3A%20string%20%7D%20%7D%3E)):
```ts
type AtomicObject =
  | Function
  | Map<any, any>
  | WeakMap<any, any>
  | Set<any>
  | WeakSet<any>
  | Promise<any>
  | Date
  | RegExp
  | Boolean
  | Number
  | String

type IsFinite<T extends any[]> = T extends never[]
  ? true
  : T extends ReadonlyArray<infer U> ? (U[] extends T ? false : true) : true

// we extracted the mapped type into its own name
export type DraftObjectReal<T> = { -readonly [P in keyof T]: Draft<T[P]> }
export type DraftObject<T> = T extends object
  ? T extends AtomicObject ? T : DraftObjectReal<T>
  : T

export type DraftArray<T> = Array<
  T extends ReadonlyArray<any>
    ? { [P in keyof T]: Draft<T> }[keyof T]
    : DraftObject<T>
>

export type DraftTuple<T extends any[]> = {
  [P in keyof T]: T[P] extends T[number] ? Draft<T[P]> : never
}

export type Draft<T> = T extends any[]
  ? IsFinite<T> extends true ? DraftTuple<T> : DraftArray<T[number]>
  : T extends ReadonlyArray<any>
    ? DraftArray<T[number]>
    : T extends object ? DraftObject<T> : T

type T0 = Draft<{ x: { y: string } }>
```

**Comment by WhiteAbeLincoln** [comment]
Its probably an upstream problem with typescript, but I'm not sure they'll fix it since it deals with type recursion and they don't really support that.

Extracting the mapped type out does seem to work, and it wouldn't break anything, so its probably a good fix

**Comment by aleclarson** [comment]
I need to figure out how to trigger a compiler error when specificity is _lost_ (ie: expected an object type, got any).

**Comment by WhiteAbeLincoln** [comment]
Yeah, I know you can use [dtslint](https://github.com/Microsoft/dtslint) to test types, but I'm not sure if it tests them exactly or just if they're assignable

**Comment by aleclarson** [comment]
This works! 🎉 
```ts
type Check<A, B> = A extends B ? (B extends A ? 1 : 0) : 0
let check = <A, B>(): Check<A, B> => b

let val = {a: 1}
let test: 1 = check<any, typeof val>()
```

**Comment by aleclarson** [comment]
I will have #244 merged in a bit.

**Comment by aleclarson** [comment]
Quick update: I'll try to find time to fix all the errors found by #244 sometime soon

**Comment by danenania** [comment]
Just trying out immer (which is fantastic, thanks!) and I seem to still be running into this with typescript 3.1.4 and immer 1.9.3.

In the following example:

``` 
type Params = {
    users?: {
      [userId: string]: {
        [parentId: string]: {[k: string]: string}
      }
    }
}

return produce(params, draft => {
   if(!draft.users)draft.users = {};
   if(!draft.users[userId])draft.users[userId] = {};
   draft.users[userId][parentId] = parent;
})
```

The inferred type of `draft` is `{ users?: any }` instead of the full `Params` type.

If I explicitly set `(draft: Params)=> ...` then I get the full nested type, but it would of course be nice to have the inference.

**Comment by aleclarson** [comment]
@danenania Confirmed on `typescript@3.1.6`. Upgrading to 3.2.x fixes it.

**Comment by danenania** [comment]
Ah great, will upgrade typescript, thanks!
