### ISSUE TITLE
Use terser instead of uglify-es

### ISSUE THREAD

**Issue by aleclarson** [mweststrate/immer#247]
@gaearon has been tweeting about `uglify-es` causing issues for CRA users. Considering `uglify-es` is unmaintained, we should use [terser](https://www.npmjs.com/package/terser) instead (a fork of `uglify-es` that is actively maintained).

**Comment by mweststrate** [comment]
Agreed

Op vr 9 nov. 2018 om 16:48 schreef Alec Larson <notifications@github.com>:

**Comment by aleclarson** [comment]
I'm not using the minified version of Immer, so I cannot set aside time to do this. 😢

**Comment by dwelle** [comment]
@mweststrate what's [this line](https://github.com/mweststrate/immer/blob/899b53f519b304652461348c06ea0a5e210cf2e7/rollup.config.js#L54) about? The `rollup-plugin-uglify` doesn't take any 2nd arg.

**Comment by mweststrate** [comment]
@dwelle no clue, probably copied it from somewhere else, but it seems to parameterize the minifier that should be used :)

**Comment by aleclarson** [comment]
We could stop bundling Immer altogether.

Bundling is the job of the application, not the library.

Web apps can use https://packd.now.sh/immer@1.8.0 or something like Webpack.

Node apps can use something like https://github.com/zeit/ncc

**Comment by prithvi16** [comment]
@mweststrate are there any contributing guidelines or local development setup instructions? I looked for them in README and wiki.

**Comment by mweststrate** [comment]
Bundling is pretty essential for UMD builds, for other builds it can be left out indeed

@prithvi16 no, no clear guidelines atm :), setup is pretty straight forward, make sure to use `yarn`  and that your IDE respects prettier, and that should be it. Discuss large changes upfront in an issue to avoid wasting effort

**Comment by aleclarson** [comment]
@mweststrate There's https://unpkg.com/ for UMD bundles.

**Comment by mweststrate** [comment]
unpkg is a CDN, not a bundler, so if you put an UMD bundle in your package,
then you can CDN UMD builds. Otherwise you have useless require / import
statements in your browser

**Comment by aleclarson** [comment]
Just realized Packd creates a UMD bundle, so I think we can stop using Rollup locally. :)

**Comment by aleclarson** [comment]
Note: https://bundle.run should be used over https://packd.now.sh

**Comment by aleclarson** [comment]
Alternatively, we could use https://github.com/developit/microbundle (if you still believe Immer should be bundled before publishing).

**Comment by mweststrate** [comment]
Oh that's cool! Didn't know it. 

Further optimization: mange properties could be used to make the minified build smaller (with exceptions for publicly exposed property names).

**Comment by aleclarson** [comment]
If anyone wants to contribute here, try setting up [bili](https://github.com/egoist/bili).

It has the same goals as [microbundle](https://github.com/developit/microbundle), but with some nice improvements: https://github.com/egoist/bili/issues/163

**Comment by egoist** [comment]
@aleclarson you can close this now as it's resolved 🤗
