### ISSUE TITLE
[RFC] Export a "produce" factory

### ISSUE THREAD

**Issue by aleclarson** [mweststrate/immer#254]
* [x] Feature request: Export a `new Immer(options)` function
  * [x] I am willing to implement this myself

## Details  

The `Immer` constructor lets you create a `produce` function with custom behavior and/or hooks.

- Promotes friendly interop between libraries using Immer
- Opens up space for niche library-specific configuration

```js
import {Immer} from 'immer'

// An example using the default values:
const {produce} = new Immer({
  useProxies: typeof Proxy !== 'undefined' && typeof Reflect !== 'undefined',
  autoFreeze: typeof process !== 'undefined' && process.env.NODE_ENV !== 'production',
  deepFreeze: false,
  hooks: {
    set(state, prop, value) {},
    delete(state, prop) {},
    copy(state) {},
  }
})

// Use `produce` like you normally would.
produce({ a: 1 }, recipe)
produce(recipe)({ a: 1 })
```

As you can see, there's plenty of room for more configuration, if and when use cases demand it.

This would supplant the need for #221.

**Comment by aleclarson** [comment]
ping @mweststrate ICYMI

**Comment by mweststrate** [comment]
@aleclarson I think that is a nice feature!
