### ISSUE TITLE
No dist folder in 1.8.1 npm package

### ISSUE THREAD

**Issue by johanventer** [mweststrate/immer#264]
1.8.1 was release 15 minutes ago, but there doesn't appear to be any actual code in the package - i.e. no dist folder. I just happened to be reinstalling all my modules at the time.

**Comment by aleclarson** [comment]
Hmm, `semantic-release` must not be configured properly.

**Comment by aleclarson** [comment]
The current `.travis.yml`:
https://github.com/mweststrate/immer/blob/e520350ab62b5e3aefa6e659b9d38e5a707988ab/.travis.yml#L13-L18

**Comment by aleclarson** [comment]
Trying https://github.com/mweststrate/immer/commit/eebe57700ccf88aeff678b9fad61648cb123cf2b on branch __issue-264__.
