### ISSUE TITLE
v1.9.0 doesn't include the typescript declarations anymore but "types" prop in package.json is still set to "./dist/immer.d.ts"

### ISSUE THREAD

**Issue by vladimiry** [mweststrate/immer#268]
The issue is self-explanatory.

So if you go with typescript you will get the following errors with v1.9.0:
```
error TS7016: Could not find a declaration file for module 'immer'
...
Try `npm install @types/immer` if it exists or add a new declaration (.d.ts) file containing `declare module 'immer';`
```

**Comment by benneq** [comment]
For me I don't get an error, but typings don't work at all. Everything is `any`. (But this may be, because I use `allowSyntheticDefaultImports`)

```
$ ls node_modules/immer/*
node_modules/immer/LICENSE	node_modules/immer/readme.md
node_modules/immer/package.json

node_modules/immer/dist:
immer.js		immer.module.js		immer.umd.js
immer.js.map		immer.module.js.map	immer.umd.js.map
```

No `d.ts` file(s), as you can see.

**Comment by aleclarson** [comment]
I found the issue. A patch will be out shortly.

Does anyone know if we can prevent a mistake like this in the future? I'm surprised that `tsc` doesn't fail when the `typings` field in `package.json` is pointing to a non-existent path.

**Comment by benneq** [comment]
How about just adding a simple test somewhere, that reads `types` from `package.json` and checks if the file exists?

**Comment by vladimiry** [comment]
> How about just adding a simple test somewhere, that reads types from package.json and checks if the file exists?

I think the more reliable approach would be in running the simplest test written in typescript with the `strict` compilation mode enabled (which is by the way default option of executing `tsc --init` command, and I'm happy that it's). This test will need to be executed on `./dist` fodler, ie be placed to the end of the build pipeline (`build` npm script), so that would be a kind of e2e test. So if such test fails we then get error exit code and so no npm pubslishing is supposed to happen. I can look into this and propose a PR.

**Comment by aleclarson** [comment]
@vladimiry I found the issue there. We can just import `../dist/immer.js` instead of `../src/index.js` inside the TypeScript test. See here: https://github.com/mweststrate/immer/pull/269/commits/1b95ea9543caa7c70989796d47fc739cd9395d76

**Comment by aleclarson** [comment]
Now I need to investigate why `yarn test:flow` was not failing.

**Comment by vladimiry** [comment]
@aleclarson 

> We can just import ../dist/immer.js instead of ../src/index.js inside the TypeScript test. See here: 1b95ea9

This is exactly what I meant. But I'd suggest enabling `strict` compilation option in [this](https://github.com/mweststrate/immer/blob/4b9b6375d8deb855eaed44a48daa808c753a93a8/__tests__/test.tsconfig.json) config.

**Comment by aleclarson** [comment]
Okay, the only thing holding this up is that `yarn test:flow` does not fail when `dist/immer.js.flow` is missing.

**Comment by aleclarson** [comment]
Thanks for the assistance @vladimiry and @benneq
