### ISSUE TITLE
Version 1.9.1 Typescript issue with generics

### ISSUE THREAD

**Issue by benneq** [mweststrate/immer#272]
Hello again :D (hope, it doesn't get annoying)

I've written a small function:
```
const insertAtIndex = <T>(array: T[], index: number, elem: T): T[] => {
    return produce(array, draft => {
        draft.splice(index, 0, elem as any); // <= need "any" for this to work :(
    });
}
```

Without using `as any` I get:
```
Argument of type 'T' is not assignable to parameter of type 'T extends ReadonlyArray<any> ? { [P in keyof T]: Draft<T>; }[keyof T] : DraftObject<T>'. ts(2345)
```

**This error only appears within this generic function in combination with Immer.**

These two cases work as expected:
```
export const insertAtIndex = <T>(array: T[], index: number, elem: T) => {
    array.splice(index, 0, elem);
}
```

```
const array = [1,2,3];
const elem = 4;
const newArray = produce(array, draft => {
    draft.splice(42, 0, elem);
})
```

**Comment by aleclarson** [comment]
Thank you for finding these edge cases! Need to improve the typescript tests, I guess.

**Comment by aleclarson** [comment]
Interestingly, when you explicitly type the `draft` parameter with `draft: T[]` (which _shouldn't_ be required), a new error appears:
```
[ts]
Argument of type 'T[]' is not assignable to parameter of type '(this: (draft: T[]) => void, draft: (draft: T[]) => void) => any'.
  Type 'T[]' provides no match for the signature '(this: (draft: T[]) => void, draft: (draft: T[]) => void): any'. [2345]
```

**Comment by benneq** [comment]
I changed the code of `DraftArray` a bit (should still have the same "meaning", right?):
Old:
```
export type DraftArray<T> = Array<
    T extends ReadonlyArray<any>
        ? {[P in keyof T]: Draft<T>}[keyof T]
        : DraftObject<T>
>
```
New:
```
export type DraftArray<T> = T extends ReadonlyArray<any>
    ? Array<{[P in keyof T]: Draft<T>}[keyof T]>
    : Array<DraftObject<T>>
```

This gives a new error message:
```
Argument of type 'T' is not assignable to parameter of type 'DraftObject<T>'. ts(2345)
```
It looks like it chooses the right conditional statement.

And with a last small change to **my** code, the error is gone.
**The change to `DraftArray` is still necessary!**
Old:
```
export const insertAtIndex = <T>(array: T[], index: number, elem: T): T[] => {
    return produce(array, draft => {
        draft.splice(index, 0, elem);
    });
}
```
New:
```
                            HERE'S THE CHANGE
                                    |
                                    v
export const insertAtIndex = <T extends any>(array: T[], index: number, elem: T): T[] => {
    return produce(array, draft => {
        draft.splice(index, 0, elem);
    });
}
```

Of course this change shouldn't be necessary here.

**Comment by aleclarson** [comment]
What typescript version are you using? Changing the `DraftArray` did not change the error for me, but `extends any` prevents the error as you said.

**Comment by benneq** [comment]
according to package.json:
```
"typescript": "3.2.2",
```

But my tsconfig.json is a bit messy, because it's a legacy project with lot's of js and a bit of ts code:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "stripInternal": true,
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noEmitHelpers": true,
    "importHelpers": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "jsx": "react",
    "lib": ["es6", "es2017", "dom", "dom.iterable", "esnext.asynciterable"]
  },
  "exclude": [
    "node_modules",
    "app/_libs",
  ]
}
```

**Comment by aleclarson** [comment]
Using typescript 3.1.4, I'm getting `[ts] Expected 1-2 arguments, but got 3. [2554]` on the `draft.splice` line. I will try with 3.2.

**Comment by aleclarson** [comment]
Using typescript 3.2.2, using your `DraftArray` has no effect. :S

**Comment by benneq** [comment]
I've now tried 3.1.4

There I also get the `Expected 1-2 arguments, but got 3. ts(2554)` error.

Here's TypeScript's `lib.es5.d.ts`:
3.1.4:
```
    splice(start: number, deleteCount?: number): T[];
    splice(start: number, deleteCount: number, ...items: T[]): T[];
```
3.2.2:
```
    splice(start: number, deleteCount?: number): T[];
    splice(start: number, deleteCount: number, ...items: T[]): T[];
```
Looks the same. Maybe it's something from my `tsconfig.json` :(

Now back at `3.2.2`:
```
$ ./node_modules/.bin/tsc --version
Version 3.2.2
```

My `node_modules` is always up to date. I update my packages using `rm -rf package-lock.json node_modules && npm i` (a bit rough, I know, but this way I'm sure that everything is up2date).

Btw: I didn't check the TypeScript console output. I just looked at VSCode. Let me recheck...
... same behavior. Error is gone with both changes.

I'll record a small video :D

**Comment by aleclarson** [comment]
Sorry, I was using a locally-linked version, which had some changes I made for #273. 😅 

Still trying to figure this out.. Maybe it's just a Typescript bug?

**Comment by aleclarson** [comment]
If you want to look into this more, you should..
- fork the `master` branch
- run `yarn && yarn test:dts --watch`
- in a new tab, run `yarn typed --watch`
- finally, try fixing any failed typescript tests by making changes to `src/immer.d.ts`

**Comment by aleclarson** [comment]
@benneq Your last change to `DraftArray` fixes the `splice` call. But now, try a `push` call.

**Comment by aleclarson** [comment]
I figured it out! 😄 See here: cb195cbd13905f6103668d9dd1204bf2984f2b9b

But there are still failing tests, so I won't publish 1.9.3 just yet.

**Comment by benneq** [comment]
Wow. That‘s huge. Will try it soon

**Comment by aleclarson** [comment]
Alright, I'm counting this as a TypeScript bug.

The best workaround is:
```ts
import produce from 'immer';

export function insertAtIndex<T>(array: ReadonlyArray<T>, index: number, elem: T): ReadonlyArray<T>
export function insertAtIndex(array: ReadonlyArray<any>, index: number, elem: any) {
    return produce(array, draft => {
        draft.splice(index, 0, elem);
    });
}
```

**Comment by mweststrate** [comment]
@benneq could you setup a small TS based code sandbox (or some other online tool), to fiddle around more easily? I suspect we might be running in a TS limitation here, no be able to expre co- versus contra- variance in generics.

**Comment by benneq** [comment]
Hi, I just downloaded you `next` branch. But give me a few minutes, I think I found a fundamental flaw within you Array typings!

Stay tuned!

**Comment by aleclarson** [comment]
@mweststrate The `next` branch already contains a test for this. So far, the issue seems to be that `Draft<T>` is _not_ assignable to `T`.

@benneq I haven't read your diagnosis yet, but that last link looks like a good road to take after v1.9.3.

**Comment by benneq** [comment]
My diagnonis can be summarized in 1 word: useless :D

Yes, maybe that‘s a better approach, but I think it won‘t fix the problem with generics.

**Comment by aleclarson** [comment]
The following behavior is really confusing me:
```ts
type A1 = [0]
type A2 = ReadonlyArray<string>

type B1 = Draft<A1> // => [0] 👍
type B2 = Draft<A2> // => string[] 👍
type B3 = Draft<A1 | A2> // => [0] | ReadonlyArray<string> 🤨
```
*Note:* If you cannot reproduce, I have local changes that I need to push. :)

**Comment by benneq** [comment]
I guess that‘s because the type T = (A1 OR A2). And this Union type is an own type.

But maybe the type of A1 is incorrect? Is it number[] or [number] or even [0] ?

—-

Had another idea: typings from immutable.js
I think i remember a similar function like process. But I could be wrong.

**Comment by aleclarson** [comment]
@benneq I deleted my comment, because it was a blunder. You can delete yours, and I'll delete this one, if you want.

**Comment by aleclarson** [comment]
Okay, the best workaround (explicit argument types) is demonstrated here:

https://github.com/mweststrate/immer/blob/d60db147173d236727f035fd31e2aac372d7bf8b/__tests__/produce.ts#L151-L163

Here are some related tests:

https://github.com/mweststrate/immer/blob/d60db147173d236727f035fd31e2aac372d7bf8b/__tests__/draft.ts#L291-L300

https://github.com/mweststrate/immer/blob/d60db147173d236727f035fd31e2aac372d7bf8b/__tests__/draft.ts#L19-L27

**Comment by aleclarson** [comment]
Thanks for the assistance, @benneq! ❤️

**Comment by benneq** [comment]
Wow. Thank you.
But I‘m pretty sure that your explicit workaround does only work for the first level. I‘ll try your code tomorrow.

But I expect that things like `draft[0].splice` won‘t work. Or you need a more complex explicit type.

**Comment by aleclarson** [comment]
@benneq Let me know in a new issue if you hit anything. :)
