### ISSUE TITLE
[TS] incorrect type inference when using curried function with initial state

### ISSUE THREAD

**Issue by aleclarson** [mweststrate/immer#273]
```ts
let fn = produce((draft: number|string) => {}, Math.random())
fn('undefined')
```

In the example above, the recipe function signature should take precedence over the initial state's type.

**Comment by mweststrate** [comment]
I had quite some issues in the past if TS needs to infer the type from something you pass to it (it usually works for direct functions if not to complex, but not beyond that). I think in general you'll be more safe by writing  
`let fn = produce<number|string>(draft => {}, Math.random())`

**Comment by aleclarson** [comment]
@mweststrate I've figured it out already. Just not pushed yet.
