### ISSUE TITLE
A tuple type element list cannot be empty

### ISSUE THREAD

**Issue by anderslyman** [mweststrate/immer#280]
Version: 1.9.3

Issue: when compiling with the Angular cli (version 6.2.2), I see the following error:
![image](https://user-images.githubusercontent.com/1380857/50250422-f1069500-039d-11e9-8ebd-e2d7a403c971.png)

Seems to be a problem in the typescript definition file.

If it's relevant, here's my tsconfig:
![image](https://user-images.githubusercontent.com/1380857/50251635-be5e9b80-03a1-11e9-88aa-a18ef9b9ef43.png)

Downgrading to 1.9.0 seems to fix the issue.

**Comment by aleclarson** [comment]
Try upgrading Angular CLI. If that doesn't work, please provide a repro. 👍

**Comment by anderslyman** [comment]
Can confirm that upgrading the Angular CLI fixes the issue.

**Comment by duanemck** [comment]
Just some more info, I was getting those exact errors. Had to upgrade the CLI as well as Angular itself. I was running 6.x, needed to upgrade to 7.x (pure CLI upgrade did nothing)

**Comment by joshkel** [comment]
I'm not using Angular, but I ran into these errors because my installed version of TypeScript was out of date. Immer requires TypeScript 3.1 or above, so the older version I was using couldn't process all of Immer's typings.

**Comment by Mohamad-Kamar** [comment]
I encountered the same error yesterday. Turns out that the bug was happening because i declared a type/interface in which i didn't use. All you have to do is to find an interface (or a type) declaration in which you are not using and comment it out (or instantiate an empty variable of that type.
