### ISSUE TITLE
nothing does not actually set a value to undefined

### ISSUE THREAD

**Issue by stevensacks** [mweststrate/immer#283]
* [x] Issue: nothing does not actually set a value to undefined, it sets it to the Symbol(immer-nothing), and thus strict equality checks for undefined fail
  * Version: 1.9.3
  * https://codesandbox.io/s/llpl2v6577
  * Expected behavior: After the state is produced, the value should be undefined
  * Observed behavior: After the state is produced, the value is Symbol(immer-nothing)
  * [x] Occurs when using Proxies (use `setUseProxies(true)`)
  * [x] Occurs in the ES5 implementation (use `setUseProxies(false)`)
  
100% reproducible.

This is a problem for redux empowered apps when you're strictly checking for undefined in your state, which is very common.

**Comment by aleclarson** [comment]
The `nothing` symbol must be the return value of your producer.

When your producer returns an object and you want one of its properties to equal `undefined`, you can use `undefined` directly without issue.

**Comment by stevensacks** [comment]
Ah, my bad.
