### ISSUE TITLE
Breaking change in produce typescript definition

### ISSUE THREAD

**Issue by grassick** [mweststrate/immer#288]
* [x] Issue: Curried TS definition allows undefined to be passed as base
  * Version: 1.10.0
  * Expected behavior: produce currying definition which returns a function that takes a first argument of type Base (the way it used to work before https://github.com/mweststrate/immer/commit/8666d32d07e9283b0abb9add5959998593b64755)
  * Observed behavior: produce currying definition that returns a function that takes Base | undefined as first parameter

The definition for the curried produce function used to be:

```
    /** Curried producer with no initial state */
    <State, Result = any, Args extends any[] = any[]>(
        recipe: (
            this: Draft<State>,
            draft: Draft<State>,
            ...extraArgs: Args
        ) => void | Result
    ): (base: State, ...extraArgs: Args) => void extends Result ? State : Result
```

It is now: 
```
    /** Curried producer */
    <Default = any, Base = Default, Rest extends any[] = [], Return = void>(
        recipe: (
            this: Draft<Base>,
            draft: Draft<Base>,
            ...rest: Rest
        ) => Return,
        defaultBase?: Default
    ): (base: Base | undefined, ...rest: Rest) => Produced<Base, Return>
```
The fact that the base can be undefined in the returned function messes up existing typescript code that doesn't expect this.

**Comment by grassick** [comment]
There are two different types of currying, I see now. Only one of the two should allow the first argument to be undefined. The more complex one with a defaultBase should still take `Base | undefined`, I think, but not the simpler one that I'm using?

**Comment by aleclarson** [comment]
Yup, I'm about to push a patch!
