### ISSUE TITLE
[v1.10.3] Immutable<T> broke my codebase

### ISSUE THREAD

**Issue by knpwrs** [mweststrate/immer#289]
Hey, there! I'm the guy that provided the original mapped type for removing `readonly` modifiers in TypeScript over in #161.

It's awesome to see this library gain so much traction since then, though the typings have also evolved to the point where I can barely recognize them. The latest patch release of `immer` broke a library I wrote (my tests pass using `immer@1.10.2` but not `immer@1.10.3`). It appears to be purely a typing thing, but I'm having a heck of a time resolving the issues. I was hoping somebody who has worked on the typings more recently than I have could give some pointers/feedback/maybe a PR against my project (or maybe we might determine that the typings are broken and not my usage and then we can fix the problem here).

The issue Greenkeeper opened against my repo can be seen here: https://github.com/knpwrs/redux-ts-utils/issues/1

This is the code that was working with `immer@1.10.2`:

```ts
export default function handleAction<S, AC extends TsActionCreator<any> = any>(
  ac: AC,
  re: TsReducer<S, ReturnType<AC>>,
  s?: S,
): Reducer<S, ReturnType<AC>> {
  return produce((draft: Draft<S>, action: ReturnType<AC>) => {
    if (action.type === ac.type) {
      re(draft, action);
    }
  }, s);
}
```

Lots of red all over the place. Here's where I've gotten so far with `immer@1.10.3`:

```ts
export default function handleAction<S, AC extends TsActionCreator<any> = any>(
  ac: AC,
  re: TsReducer<S, ReturnType<AC>>,
  s?: S,
): Reducer<S, ReturnType<AC>> {
  return produce<S, Draft<S>, [ReturnType<AC>]>((draft, action) => {
    if (action.type === ac.type) {
      re(draft, action);
    }
  }, s);
}
```

Now the only thing that is red is that second-to-last line where I'm passing `s` as the default value to `produce`. TypeScript complains:

```
Argument of type 'S | undefined' is not assignable to parameter of type 'S'.
  Type 'undefined' is not assignable to type 'S'.
```

Nothing I'm trying is resolving the issue (even type casting or the dreaded `!` operator which results in more errors). I want `s` to remain an optional parameter.

Any ideas?

**Comment by aleclarson** [comment]
As a quick fix, you can do `produce(...) as any`. Can you come up with a simpler repro that we can add as a test case?

**Comment by knpwrs** [comment]
I wound up having to do `s as S` as well as casting the whole `produce()` call `as any`:

```ts
  return produce<S, Draft<S>, [ReturnType<AC>]>((draft, action) => {
    if (action.type === ac.type) {
      re(draft, action);
    }
  }, s as S) as any; // see https://github.com/mweststrate/immer/issues/289
```

> Can you come up with a simpler repro that we can add as a test case?

I'll see if I can come up with something real quick.

**Comment by aleclarson** [comment]
```
Type 'S | undefined' is not assignable to type 'Immutable<Draft<S>> | undefined'.
```

The issue is that `Immutable<Draft<S>>` can't be simplified to `S` because it's a generic parameter.

By default, Immer freezes any object it makes a copy of. I recently changed the type signature of `produce` to better reflect this. I changed its return type to be a __deeply__ immutable version of the draft state type. Clearly, this has broken some assumption(s) that some users (like yourself) have made about Immer. Now the question is, would it be better to (1) remove the `Immutable<T>` type I've added and give users the responsibility of making their object types deeply immutable, or (2) figure something else out.

Having `produce` always return a deeply immutable type is preferrable IMO, because you're "not supposed to" be making mutations outside of Immer.

Does Redux not enforce immutability in its type defs?

**Comment by aleclarson** [comment]
This works on my end:
```ts
  return produce((draft: Draft<S>, action: ReturnType<AC>) => {
    if (action.type === ac.type) {
      re(draft, action);
    }
  }, s) as any;
```

**Comment by knpwrs** [comment]
No, the `readonly` modifier does not appear anywhere in redux: https://github.com/reduxjs/redux/blob/632da6c902d2637082f197669a7e81bd3aaba7b3/index.d.ts

**Comment by knpwrs** [comment]
> This works on my end

Ah, nice. That gets me back to the original non-diamond syntax. I was moving forward with moving the types to the diamond.

**Comment by aleclarson** [comment]
Interesting. Yet, the Redux docs say [immutability is required](https://redux.js.org/faq/immutable-data#why-is-immutability-required-by-redux). Maybe Redux should enforce immutability in its types like Immer does?

cc @gaearon

**Comment by markerikson** [comment]
I'll quote my post [The Tao of Redux, Part 1: Implementation and Intent](https://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-1/):

> The core Redux `createStore` function itself puts only two limitations on how you must write your code: actions must be plain objects, and they must contain a defined `type` field.  It does not care about immutability, serializability, or side effects, or what the value of the `type` field actually is.
> 
> That said, **the commonly used pieces around that core, including the Redux DevTools, React-Redux, React, and Reselect, _do_ rely on proper use of immutability, serializable actions/state, and pure reducer functions**.  The main application logic may work okay if these expectations are ignored, but it's very likely that time-travel debugging and component re-rendering will break.  These also will affect any other persistence-related use cases as well.
> 
> It's also important to note that **immutability, serializability, and pure functions are not enforced in any way by Redux**.  It's entirely possible for a reducer function to mutate its state or trigger an AJAX call.  It's entirely possible for any other part of the application to call `getState()` and modify the contents of the state tree directly.  It's entirely possible to put promises, functions, Symbols, class instances, or other non-serializable values into actions or the state tree.  You are not _supposed_ to do any of those things, but it's _possible_.

**Comment by aleclarson** [comment]
@markerikson In the context of TypeScript, I don't see the benefit of not enforcing immutability. You can easily use `as any` as an escape hatch.

**Comment by markerikson** [comment]
I don't use TS yet myself, so I don't know what the typings do or don't say.

**Comment by aleclarson** [comment]
Have you done a Twitter poll asking which Redux users are using TypeScript with it? Anyway, if Redux users aren't making a fuss about lack of deep immutability enforcement, then it's probably not a big issue. Anyone using Redux and Immer together will need to use `as any` when using generic parameters.

**Comment by jineshshah36** [comment]
I don't understand what the purpose of https://github.com/mweststrate/immer/releases/tag/v1.10.3 was, but it has broken every single produce I'm using throughout my TS app. The types seem to be broken because it converts everything to any types. It looks like the `Immutable` generic type is not written correctly

**Comment by aleclarson** [comment]
@jineshshah36 That sounds awful. Can you provide some examples of how you're using Immer? I would love to help you out. 😉

**Comment by jineshshah36** [comment]
I appreciate the quick response! Here is an example:

```typescript
import { produce } from "immer"

interface X {
  a: {
    [k: string]: {
      id: string
      message: string
      created_at: string
      updated_at: string
      client_id: string
      owner_id: string
      creator_id: string
      creator: {
        first_name: string
        last_name: string
      }
      deleted_at: null | string
      reminder_at: null | string
      notified_at: null | string
      via: null | string
      notification_ids: null | string[]
    }
  }
}

const x = (state: X, action: { type: "test" }) =>
  produce(state, draft => {
    switch (action.type) {
      case "test": {
        draft.a.test = {
          id: "",
          message: "",
          created_at: "",
          updated_at: "",
          client_id: "",
          owner_id: "",
          creator_id: "",
          creator: {
            first_name: "",
            last_name: "",
          },
          deleted_at: null,
          reminder_at: null,
          notified_at: null,
          via: null,
          notification_ids: ["hi"],
        }
      }
    }
  })
```

the type of x  is:

```typescript
(state: X, action: { type: "test" }) => { readonly a: any }
```

**Comment by aleclarson** [comment]
@jineshshah36 The easiest workaround is doing `produce(...) as X`. Is there a reason you don't want Immer to return a deeply immutable object (other than your code isn't setup for it currently)? You're not really supposed to mutate your state outside of an Immer producer.

**Comment by jineshshah36** [comment]
I agree, but the type of x should be. Using "as" is somewhat an anti-pattern because it breaks type-safety.

```typescript
(state: X, action: { type: "test" }) => {
  readonly a: {
    [k: string]: Readonly<{
      id: string
      message: string
      created_at: string
      updated_at: string
      client_id: string
      owner_id: string
      creator_id: string
      creator: {
        first_name: string
        last_name: string
      }
      deleted_at: null | string
      reminder_at: null | string
      notified_at: null | string
      via: null | string
      notification_ids: null | string[]
    }>
  }
}
```

not:

```typescript
(state: X, action: { type: "test" }) => { readonly a: any }
```

**Comment by aleclarson** [comment]
> Using "as" is somewhat an anti-pattern because it breaks type-safety.

It's definitely not the first thing you should jump to. ;)

What version of TypeScript are you on?

**Comment by markerikson** [comment]
So it looks like this issue may be relevant to me after all.

We're working on converting https://github.com/reduxjs/redux-starter-kit to TS.  The PR adds "typing tests".  One of them is currently exploding:

```
    Semantic: D:/Projects/redux/redux-starter-kit/src/createReducer.ts (51, 5) Type 'Immutable<S>' is not assignable to type 'S'.
      Type 'S | (S extends AtomicObject ? S : S extends ReadonlyArray<any> ? S[number][] extends S ? { [P in keyof S]: ReadonlyArray<Immutable<S[number]>>; }[keyof S] : ImmutableTuple<S> : { readonly [P in keyof S]: Immutable<S[P]>; })' is not assignable to type 'S'.
        Type 'S extends AtomicObject ? S : S extends ReadonlyArray<any> ? S[number][] extends S ? { [P in keyof S]: ReadonlyArray<Immutable<S[number]>>; }[keyof S] : ImmutableTuple<S> : { readonly [P in keyof S]: Immutable<S[P]>; }' is not assignable to type 'S'.
          Type '(Function & object & S) | (String & object & S) | (Number & object & S) | (Boolean & object & S) | (RegExp & object & S) | (Date & object & S) | (Promise<any> & object & S) | ... 4 more ... | (S extends ReadonlyArray<...> ? S[number][] extends S ? { [P in keyof S]: ReadonlyArray<...>; }[keyof S] : ImmutableTuple<......' is not assignable to type 'S'.
            Type 'S extends ReadonlyArray<any> ? S[number][] extends S ? { [P in keyof S]: ReadonlyArray<Immutable<S[number]>>; }[keyof S] : ImmutableTuple<S> : { readonly [P in keyof S]: Immutable<S[P]>; }' is not assignable to type 'S'.
              Type '(S[number][] extends S ? { [P in keyof S]: ReadonlyArray<Immutable<S[number]>>; }[keyof S] : ImmutableTuple<S>) | { readonly [P in keyof S]: Immutable<S[P]>; }' is not assignable to type 'S'.
                Type 'S[number][] extends S ? { [P in keyof S]: ReadonlyArray<Immutable<S[number]>>; }[keyof S] : ImmutableTuple<S>' is not
assignable to type 'S'.
                  Type '{ [P in keyof S]: ReadonlyArray<Immutable<S[number]>>; }[keyof S] | ImmutableTuple<S>' is not assignable to type 'S'.
                    Type 'ReadonlyArray<Immutable<S[number]>>' is not assignable to type 'S'.
```

Looks related.

Suggestions?

**Comment by aleclarson** [comment]
> Actually, 3.2 breaks JSX resolution which breaks many react related libraries and apps.

Is there an issue tracking this in the TypeScript repo?

> In addition, if it does work in 3.2, this update should be a breaking change not a bugfix.

It's more-so that 3.2 fixed a bug that 3.1 had involving recursive types, I think.

**Comment by alitaheri** [comment]
This broke a lot of code, why should we enforce immutibility at type level?

I understand that it's a good practice, but this means a lot of things:
I can't reuse interfaces for both mutable and immutable data structures.
I have to explicitly type the draft as it's broken.
Arrays are now ReadonlyArrays which is very painful to work with.

If someone want's to explicitly type their state as readonly let them be. why should we *dictate* the way programs are built?

@mweststrate @aleclarson There are way too many constraints imposed by this change. Please don't let this awesome project drift away from it's community.

**Comment by knpwrs** [comment]
> Is there a reason you don't want Immer to return a deeply immutable object (other than your code isn't setup for it currently)?

I personally think it makes sense for `immer` to transparently return whatever it is given. Before #161 it wasn't even possible to use `readonly`, requiring `readonly` (or enforcing it on the output) seems like a semver major change.

**Comment by aleclarson** [comment]
> - I can't reuse interfaces for both mutable and immutable data structures.
> - I have to explicitly type the draft as it's broken.
> - Arrays are now ReadonlyArrays which is very painful to work with.

Please provide examples to back these claims. Thanks!

&nbsp;

> If someone want's to explicitly type their state as readonly let them be. why should we dictate the way programs are built?

The rationale is that deep immutability is better, because it fits the default behavior of Immer. If you're using `setAutoFreeze(false)`, then you need to "cast" the result of your `produce` calls back to the mutable type you're expecting.

I wouldn't be opposed to adding a `mutableProduce` export that has less strict typing. Then you could do `import { mutableProduce as produce } from 'immer'`. Thoughts?

&nbsp;

> Please write exhaustive ts tests before changing the types, there are too many ts breaks and amendments recently

Not sure how to verify the exhaustiveness of the current test suite. Any recommendations? Please contribute some tests that you feel are missing.

&nbsp;

> I personally think it makes sense for `immer` to transparently return whatever it is given. Before #161 it wasn't even possible to use `readonly`, requiring `readonly` (or enforcing it on the output) seems like a semver major change.

Apart from pesky generic types, how else is deep immutability causing issues? I'm leaning towards the opinion that any code broken by deep immutability wasn't written correctly in the first place, but feel free to prove me wrong.

**Comment by knpwrs** [comment]
> I'm leaning towards the opinion that any code broken by deep immutability wasn't written correctly in the first place, but feel free to prove me wrong.

I wouldn't disagree on principle, but I think immer falls more on the "tool" end of the spectrum of `tool <=> opinionated framework`, if that makes sense.

I'd also still argue that such a change would merit a semver major release.

**Comment by aleclarson** [comment]
> I wouldn't disagree on principle, but I think immer falls more on the "tool" end of the spectrum of `tool <=> opinionated framework`, if that makes sense.

Immer is specifically a tool for working with deeply immutable trees, so it's not really pushing an opinion on anyone by enforcing immutability in its type defs, IMO.

> I'd also still argue that such a change would merit a semver major release.

This seems like a gray area. While this change obviously breaks some assumptions, it's questionable whether those assumptions were ever officially supported in the first place. I'm open to moving this change to 2.0 if @mweststrate agrees or you can provide a compelling use case that deep immutability prevents.

**Comment by aleclarson** [comment]
I appreciate the feedback very much! I wonder, would you guys have provided feedback if I asked before making this change? Often, people are only willing to give feedback _after_ something breaks, since it gets brought to their immediate attention. Though, I promise this wasn't my intention.

For now, I will revert this change and consider less heavy-handed approaches.

Again, thanks for the feedback! ❤️

**Comment by jineshshah36** [comment]
I am definitely willing to give feedback moving forward if you would like. You’ve shown yourself to be quite understanding and patient, which I appreciate. Thanks for building an awesome lib!

**Comment by aleclarson** [comment]
@alitaheri I appreciate you taking the time to respond despite this issue being resolved! 👏 It's good to know what Immer users expect from the library. Cheers 🍻

**Comment by mweststrate** [comment]
I totally lost track of this issue, but in the future (Immer 5.3 and up) their will be always a bail out on the produced types through the utilities `castDraft` and `castImmutable` which makes it possible to obtain either variant of the source type you want.
