### ISSUE TITLE
[1.10.4] returned type isn't as expected

### ISSUE THREAD

**Issue by michelbitter** [mweststrate/immer#290]
After updating Immer to version **1.10.4**. I'm running into a couple of typing errors on typescript.

**example code:**

```[ts]
import produce from 'immer'

export interface ConditionHandlerOutput {
  readonly errorMsg: string[],
  readonly success: boolean,
}

const stateList: ConditionHandlerOutput[] = []

// `x` cannot be modified here
const state: ConditionHandlerOutput = {
  errorMsg: [],
  success: true,
}

const newState = produce(state, draft => {
  // `x` can be modified here
  draft.errorMsg.push('This is a random string')
  draft.success = false
})

stateList.push(newState)
```

**Expected behaviour:** `newState` has type: `ConditionHandlerOutput`

**Observed behavior:** `newState` hasn't the expected type and given type is not comparable. Returned typ is: 
```[ts]
const newState: {
    readonly errorMsg: ReadonlyArray<string>;
    readonly success: boolean;
}
```

**Comment by aleclarson** [comment]
The default behavior of Immer is to freeze any objects it creates a copy of.

Can you explain what you're doing with `newState` that was broken by the recent changes?

Related: #289
