### ISSUE TITLE
Usage question - check for nested properties' existence on objects

### ISSUE THREAD

**Issue by avalanche1** [mweststrate/immer#292]
* [x ] Feature request: check for nested properties' existence on objects
Is it possible to check for deeply nested props existence using Immer similar to what some immutable micro-libs do?
examples: 
- https://github.com/herrstucki/sprout/#retrieving-nested-values
- https://github.com/steadicat/mutatis

**Comment by mweststrate** [comment]
No, that is not the goal of this project; we  want to stick to normal
javascript behavior for objects and arrays. But probably you could add for
example the nevernull package to the mix if you want.

Not that the optional chaining is an ongoing effort and might make it into
the language in the future:
https://github.com/tc39/proposal-optional-chaining/blob/master/README.md

Op do 17 jan. 2019 10:46 schreef KatKatKat <notifications@github.com>:

**Comment by avalanche1** [comment]
Thank you, was looking for smth like `nevernull`!
Waiting eagerly when this proposal lands into the standard but it's only stage-1 :(
