### ISSUE TITLE
TypeError trying to console.log the draft

### ISSUE THREAD

**Issue by peterbe** [mweststrate/immer#294]
* [ ] Feature request: No
  * [ ] I am willing to implement this myself
* [ ] Issue: this issue
  * Version: 1.10.5
  * _SIMPLE_ Reproduction: https://codesandbox.io/s/p39m2r54w0
  * Expected behavior: No TypeError
  * Observed behavior: `TypeError: illegal operation attempted on a revoked proxy`
  * [ ] Occurs when using Proxies (use `setUseProxies(true)`) (Don't know)
  * [ ] Occurs in the ES5 implementation (use `setUseProxies(false)`) (Don't know)
  
The codesandbox does a good job of reproducing it every time. Open the Web Console to see the error. Here's the code:

```javascript
const text = this.refs.text.value.trim();
if (text) {
  const tasks = produce(this.state.tasks, draft => {
    draft.push([false, { text, date: new Date() }]);
    console.log(draft);   // THIS causes the TypeError
  });
  this.setState({ tasks }, () => {
    this.refs.text.value = "";
  });
}
```

Note that the console.log actually works. It does print out: `Proxy { <target>: (1) […], <handler>: {…} }`

In Firefox I get:
```
TypeError: illegal operation attempted on a revoked proxy
```

In Chrome I get:
```
Uncaught TypeError: Cannot perform 'getPrototypeOf' on a proxy that has been revoked
```

**Comment by aleclarson** [comment]
This seems like a "bug" with `console.log` (or maybe just a caveat). You'd think it would "capture" its arguments synchronously, even if printing is done asynchronously. It seems they didn't take revocable proxies into account when implementing.

**Comment by mweststrate** [comment]
@peterbe, no, it is just a limitation of console.log, and also happens when not using proxies, super trivial example:

https://twitter.com/mweststrate/status/1086285032258523144

**Comment by peterbe** [comment]
By the way, I [blogged about Immer](https://www.peterbe.com/plog/using-immer-to-handle-nested-objects-in-react-state) and mentioned this as a caveat to be aware of. 
Thank you guys!

**Comment by macabeus** [comment]
Just commenting here to help if someone arrived here by google.... You can use `current` function from immer 7:
```js
console.log(current(draft))
```
