### ISSUE TITLE
applyPatches with inverse patches throws exception

### ISSUE THREAD

**Issue by avy-the-one** [mweststrate/immer#295]
**Description**:

When trying to `applyPatches` with inverse changes i got an exception.
```javascript
const inverseChanges = [];
const initalState = {
  value: "test"
};
const nextState = produce(
  initalState,
  s => {  s.value = "updated";  },
  (_, ip) => { inverseChanges.push(ip); }
);
const revertedState = applyPatches(nextState, inverseChanges); // EXCEPTION
```
**Version**: 1.10.5
**Reproduction link:** https://codesandbox.io/s/lpn2x2j8r9
**Observer behavior:** `TypeError: Cannot read property 'length' of undefined`
**Expected behavior:** should apply patches and revert state
**Occurs when using Proxies (use `setUseProxies(true)`)**: yes
**Occurs in the ES5 implementation (use `setUseProxies(false)`)**: yes

**Comment by aleclarson** [comment]
The `ip` parameter is an array. 😄
