### ISSUE TITLE
How to reset draft to initial state in reducer?

### ISSUE THREAD

**Issue by CodingPapi** [mweststrate/immer#296]
const initialState = {
};
const reducer = produce((draft, action) => {
  switch (action.type) {
      case 'reset': {
          draft = initialState;
          break;
      }
}, initialState);

draft = initialState not work, how can we reset draft to initial state in convenient?

Thank  you

**Comment by mweststrate** [comment]
return initialState

Op zo 20 jan. 2019 04:47 schreef CodingPuppy <notifications@github.com>:

**Comment by CodingPapi** [comment]
Thank you!

**Comment by lizagilman** [comment]
How is it possible to reset to initial state and then change a property of the draft?
To be equivalent to - 
`draft = { ...initialState,  someProp: 'newVal' } `

Thanks!

/cc @mweststrate

**Comment by mweststrate** [comment]
Use: return { stuff }

Op wo 8 jan. 2020 07:42 schreef lizagilman <notifications@github.com>:

**Comment by lizagilman** [comment]
Thanks for the quick reply @mweststrate .
 
I can `return  { ...initialState, someProp: 'newVal' }`, but I would like to get rid of the spread syntax.

Here is my initial state:
```
const initialState = {
  logs: {
    error: false,
    errorMessage: '',
    pending: false,
    fulfilled: false,
    lines: '',
  },
};
```
and I would like to first reset to this state and then update `lines`.

One way I can do that - 
`return { logs: { ...initialState.logs, lines: action.payload.data } }`

Another way (which I'm not 100% sure is right) - 
```
draft.logs = { ...initialState.logs };
draft.logs.lines = action.payload.data;
```

What would be the best way to do that? Can it be done without using spread?

Thanks.

**Comment by mweststrate** [comment]
@lizagilman please open new issues for new questions, as this one is closed already

**Comment by mweststrate** [comment]
(didn't notice that before as I was replying from mail, but replying to closed issues makes your problem invisible for everybody except those that are already in the convo, which is an completely unnecessary burden to the people already in this issue)
