### ISSUE TITLE
[QUESTION] Can I create fields that don't exist when editing draft?

### ISSUE THREAD

**Issue by mohsinulhaq** [mweststrate/immer#297]
I just have a quick question.
Before using immer, I would do this:
```javascript
draft= {
    ...draft,
    updates: {
        ...draft.updates,
        [id]: {
            ...draft.updates[id],
            done: true
        }
    }
};
```
`draft.updates[id]` can or cannot exist. And above code just works.
And now:
```javascript
// can't just do `draft.updates[id].done = true;` since `draft.updates[id]` might not exist yet.
const update = draft.updates[id];
if (!update) {
    draft.updates[id] = {
        done: true
    };
} else {
    draft.updates[id].done = true;
}
```
I have to use if else like this. I wish there was a way to create object paths that don't exist. Am I using immer incorrectly? Because this just feels ugly.

**Comment by mweststrate** [comment]
Duplicate, see: https://github.com/mweststrate/immer/issues/292#issuecomment-455189768
