### ISSUE TITLE
Immer don't break upper refs in the tree

### ISSUE THREAD

**Issue by Attrash-Islam** [mweststrate/immer#299]
Hi @mweststrate 👋 
Thanks for this awesome library ❤️ 

I had a tiny issue (Maybe I'm using immer in wrong way)

* Issue: Immer as a immutable library don't break reference as immutable structures works in all the levels.
  * Version: latest
  * _SIMPLE_ Reproduction: https://codesandbox.io/s/rmqk0460rp
  * Expected behavior: To break the ref in top level so we can check for changes by using ref equality (===) in each level.
  * Observed behavior: Immer share the same refs for the upper levels.

Compared to `lodash/fp#set`:

![image](https://user-images.githubusercontent.com/7091543/51519951-06526180-1e2b-11e9-960e-b52ec8342614.png)

This means that using immer in reducer don't break the ref of state which may be problematic in Redux concepts. (Doesn't redux reducer know about state changes by ref equality and because of that they require to return new refs?) 

Thanks in advance

**Comment by KaRkY** [comment]
Your change function is wrong you used state instead of draft.
'''
const immerNewState = produce(state, draft => {
  state.hi.how[0].are[1] = 5;
});
'''

It should be:
'''
const immerNewState = produce(state, draft => {
  draft.hi.how[0].are[1] = 5;
});
'''

**Comment by Attrash-Islam** [comment]
It's working now!! Thank you

![image](https://user-images.githubusercontent.com/7091543/51521051-13bd1b00-1e2e-11e9-9716-ae38d901b8f8.png)
