### ISSUE TITLE
immer not working in repl.it? and codesandbox demo broken

### ISSUE THREAD

**Issue by sw-yx** [mweststrate/immer#300]
* [ ] Issue: produce function is mutating its base in repl.it?
  * Version: 1.12
  * _SIMPLE_ Reproduction: https://repl.it/@swyx/LuminousRobustConditionals
  * Expected behavior: immer should not mutate the base object passed to it
  * Observed behavior: the base object is mutated
* occurs with `setUseProxies` true AND false

hey all, this is a very weird problem and i dont know if its rep.it or immer's issue. when i write:

```js
const {produce} = require('immer')
const val1 = {foo: {bar: 'baz'}}
let val2 = produce(val1, draft => {
  draft.foo = 'SWYX'
})
console.log({val1})
console.log({val2})
```

I expect `val1` and `val2` to be different, but here they are the same. am i getting the immer API wrong somehow? 

---

EDIT: i see the same problem in immer's current codesandbox: https://codesandbox.io/s/vmxmn8omwl and i have to set `setUseProxies(true)` in order for it to work in codesandbox

![Uploading image.png…]()

**Comment by sw-yx** [comment]
interestingly, it works fine in frontarmory... https://frontarm.com/demoboard/?id=12187c7f-507a-41e1-b0e3-caa4a5d0e9fb

**Comment by aleclarson** [comment]
Looks like the CodeSandbox link has an outdated `immer` dependency. If you found that in the Egghead tutorial, @mweststrate will need to update it.

Does repl.it have a debugger? Hard to debug this without one.

**Comment by sw-yx** [comment]
re: codesandbox demo

no i got that off your new issues template:
![image](https://user-images.githubusercontent.com/6764957/51655052-c46f0b80-1f4f-11e9-92d0-c8c517d72148.png)

re: repl.it - i dont know either, i'm not sure how to make it debuggable as i cant find instructions on how to do that. i have reported it on their forums though: https://repl.it/talk/ask/Why-does-this-JS-code-using-immer-not-work/10194/23705

right now i'm not sure if the issue is in immer or in repl.it, which is making this hard to diagnose :(

**Comment by mweststrate** [comment]
Fixed the code sandbox, beyond that it looks like an repl.it issue. But it is unclear how to debug in the repl.it, so that makes it a bit unclear how to dive further into the issue. At least made the error more apparent here: https://repl.it/repls/AttentiveSvelteGzip

**Comment by mweststrate** [comment]
Can also confirm that the issue isn't reproducible when running locally, on linux / node 9.7.1

**Comment by sw-yx** [comment]
alright. will close issue here and let them figure it out. disappointing, this is the first time i have ever had replit let me down.
