### ISSUE TITLE
Return the same instance with spread operator and return

### ISSUE THREAD

**Issue by benneq** [mweststrate/immer#303]
* [x] Feature request: ______
  * [ ] I am willing to implement this myself
* [x] Issue: _______
  * Version: 1.12.1
  * _SIMPLE_ Reproduction: https://codesandbox.io/s/xv5vp80vnp
  * Expected behavior: `base === next`
  * Observed behavior: `base !== next`
  * [x] Occurs when using Proxies (use `setUseProxies(true)`)
  * [x] Occurs in the ES5 implementation (use `setUseProxies(false)`)
  
I have some code that relies on `base === next`, but also needs "unknown" modifications to the object. That's where I'd like to use the spread operator in combination with `return`.
(Same problem happens when using spread without `return`: `draft.bar = {...draft.bar}`)

I know that spread returns a completely new object. But is it somehow possible to detect it, and return the original one, if it has the same content?

**Comment by mweststrate** [comment]
Use object.assign(draft, { stuff})

Op vr 25 jan. 2019 21:25 schreef Benjamin Makus <notifications@github.com>:

**Comment by mweststrate** [comment]
Note btw that the whole point of immer is that you can just do: draft.foo =
42

Op vr 25 jan. 2019 21:36 schreef Michel Weststrate <mweststrate@gmail.com>:

**Comment by benneq** [comment]
`Object.assign` only works when there's no nesting.

This is equal:
```
const base = { foo: 42, bar: { baz: true } };
const next = produce(base, draft => {
    Object.assign(draft.bar, { baz: true });
});
```

This is not equal:
```
const base = { foo: 42, bar: { baz: true } };
const next = produce(base, draft => {
    Object.assign(draft, { bar: { baz: true }});
});
```

I guess, then I have to traverse my object tree manually and use `Object.assign` on each level of the hierarchy.

**Comment by aleclarson** [comment]
Try this: https://www.npmjs.com/package/assign-deep

**Comment by benneq** [comment]
Thank you. This should do exactly what I described 👍
