### ISSUE TITLE
How to notify `mark as changed` with no state change?

### ISSUE THREAD

**Issue by hrsh7th** [mweststrate/immer#304]
* [x] Feature request: Providing way to notify `mark as changed`.
  * [ ] I am willing to implement this myself

I tring implementing https://github.com/hrsh7th/immer-deps.
It has feature that mutate part of state with no state change.

I thought should use `Object.assign` or `{ ...partOfState }`.
But I worry it's safety way to apply class instances.

I hope immer provide this safety way like this.

```ts
import { produce, markAsChanged } from 'immer';

const state = {
  tasks: [{
    id: 1,
    name: 'task1'
  }]
};

const next = produce(state, state => {
  markAsChanged(state.tasks[0]);
});

expect(next.tasks[0]).not.toEqual(state.tasks[0]);
```

Would you let me know what your thoughts are on this matter?

**Comment by hrsh7th** [comment]
Sorry, I wrong explanation.
Your intended is right for esnext environment.

But I think even so not enough to es5 environment.

immer has well supported by createHiddenProperty for environment that has not symbol.

I want to use this implemenatation.

I try to solve this by Object.defineProperty, but it's not allow to use immer's draft.

But I don't now how to use this from userland.

_I am sorry for my poor english_

**Comment by aleclarson** [comment]
For es5 environments, you can use a string like `"__$immer-deps:changed"` which has zero chance of conflicting with your users' data. Immer itself uses this strategy in es5 environments.

https://github.com/mweststrate/immer/blob/d41be775b4e8b995c74cb82276f9bd9be72072ae/src/common.js#L6-L9

But it kinda sucks that all objects used with your library would then have a weird-looking enumerable property added to them, so I see where you're coming from.

It's up to @mweststrate whether a `markChanged` function should be supported by Immer. It would only add like 5 lines to the codebase, but it's really only useful to your library.

You could always fork Immer and export something like:
```js
import {DRAFT_STATE} from './lib/common'
export function markChanged(draft) {
  const state = draft[DRAFT_STATE]
  if (state) state.modified = true
}
```

**Comment by hrsh7th** [comment]
I first thought immer provide this feature is better(natural) way.

But certainly this feature is not useful for other someone maybe... and I hope immer keep small as possible.

So this PR closable to me.
(I'll try to solve my problem by other way.)

Thank you very much for your time.
