### ISSUE TITLE
Pattern for mobx-style actions in immer

### ISSUE THREAD

**Issue by scriby** [mweststrate/immer#310]
The broader context for this is that I've been doing some exploration & experimentation around creating an Immer-based state tree (probably on a similar wavelength as mobx-state-tree). 

The state would live in a single immutable object, and actions (which are just functions) would be allowed to mutate a draft of the state with Immer. After doing so, the state would be replaced and downstream code would be made aware of changes. (I know this is similar to redux, but I'm experimenting with alternatives.)

That's all great, but I've been trying to see how easy I could make it to write async actions. Something like this works...

```js
const loadData = action((draft, url) => {
  draft.isLoading = true;
  fetch(url).then(res => res.text()).then(loadSuccess);
});

const loadSuccess = action((draft, contents) => {
  draft.isLoading = false;
  draft.contents = contents;
});
```

But I was wondering if I might be able to get something working with async/await that wouldn't require arbitrarily chunking the code up. It would be cool if something like this worked:

```js
const loadData = action(async (draft, url) => {
  draft.isLoading = true;

  const res = await fetch(url);
  const contents = await res.text();
  
  draft.contents = contents; // This isn't going to work
});
```

The only thing I could think of to make something like this work is something like this...

```js
const loadData = action(async (ctx, url) => {
  ctx.draft.isLoading = true;

  const res = await resume(fetch(url));
  const contents = await resume(res.text());
  
  ctx.draft.contents = contents;
});
```

The resume function would tell my code to go ahead and commit the draft, and update context.draft with a new draft when the promise resolves. I think the resume function can figure out which context to update based on the last action that was executed within the current event loop run.

This solution isn't completely satisfying, so I was wondering if you had any ideas or things to try out.

Hopefully this made some sense, and thanks for taking a look!

**Comment by scriby** [comment]
After a bit fo experimentation I think I found a bit better pattern for this. You can check it out at https://github.com/scriby/stimmer/blob/5cbbcdf7b1ca2c42087f23c6c8234f17692e4a4b/src/feature.test.ts#L43-L56 if you'd like.

There are some trade-offs & constraints, but I think they're all manageable. Let me know if you have any thoughts or feedback.

**Comment by hrsh7th** [comment]
I guess @scriby opinion is to detect multiple times modifications in one `produce` call.

```ts
const next = produce(state, async state => {
  state.isLoading = true;
  // <- hope to detect `"isLoading" is modified` before next async process finish.
  state.todos = await fetchTodos();
  state.todos.isLoading = false;
  // <- hope to re-detect `"todos" and "isLoading" is modified`.
});
```

I think immer can detect multiple draft modifications by separated ticks is very useful.
but it maybe break immer's mental model.
I have no idea to design nicer api.

**Comment by aleclarson** [comment]
You would need a library that wraps Immer with another layer of proxies so you can swap out the draft before the outermost promise is resolved.

**Comment by scriby** [comment]
Thanks for the suggestions everyone! I'm going to keep playing around with this. I'll go ahead and close this out to get it out of the issues list, but feel free to share more ideas.

**Comment by k644606347** [comment]
stimmer looks interesting
