### ISSUE TITLE
Idea: introduce `producer` to make working with immutable classes easier

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/immer#311]
When creating `immerable` classes, it is still pretty verbose to define functions that produce new instances. For example: 

```javascript
import {produce, immerable} from "immer"

class Clock {
    constructor(hours = 0, minutes = 0) {
        this.hours = hours
        this.minutes = minutes
    }

    increment(hours, minutes = 0) {
        return produce(this, d => {
            d.hours += hours
            d.minutes += minutes
        })
    }
}
Clock[immerable] = true
```

The `increment` function has quite some boilerplate, which can be avoided by introducing a `producer` utility, that takes out the boilerplate and stores an immerized version of the function on the prototype:

```javascript
import {producer} from "immer"

class Clock {
    constructor(hours = 0, minutes = 0) {
        this.hours = hours
        this.minutes = minutes
    }

    increment(hours, minutes = 0) {
        this.hours += hours
        this.minutes += minutes
    }
}
producer(Clock.prototype, "increment") 
```

And, if the build setup supports decorators through TypeScript or Babel, that could be simplified to: 

```javascript
import {producer} from "immer"

class Clock {
    constructor(hours = 0, minutes = 0) {
        this.hours = hours
        this.minutes = minutes
    }

    @producer
    increment(hours, minutes = 0) {
        this.hours += hours
        this.minutes += minutes
    }
}
```

N.b. not entirely happy with the `producer` name, bike shedding welcome. 

Also, not entirely sure if `[immerable]` should be set automatically by `producer`, or that it should be a prerequisite.
  
N.b.: to clarify the behavior:
```javascript
const midnight = new Clock()
const lunch = midnight.increment(12, 30)
    
expect(midnight).not.toBe(lunch)
expect(lunch).toBeInstanceOf(Clock)
expect(midnight.toString()).toBe("00:00")
expect(lunch.toString()).toBe("12:30")
```

See #312 for implementation details

**Comment by aleclarson** [comment]
We should wait for more support from the community before adding this feature.

It's easy enough to do this:
```js
const midnight = new Clock()
const lunch = produce(midnight, clock => {
  clock.increment(12, 30)
})
```

**Comment by mweststrate** [comment]
Agreed, let's close for now until there is more demand. Decorators still aren't standardized anyway.
