### ISSUE TITLE
Initial state immutability

### ISSUE THREAD

**Issue by ivi-hamiti** [mweststrate/immer#313]
I am currently exploring immer for a use case of improving an component performance with immutability and angular OnPush change detection. I encountered a strange thing with the auto freezing (which by documentation is as expected) and wanted to know if this is a normal approach or i am pushing to make something work which is not the approach expected by immer.

So i have a complex component state (deeply nested). The sub properties of the object are not created as immutable using the produce but by simple object notation. When produce is called on the state, and the property values are set, immer will only freeze the setter/getter but not the value (which is an object).

I wanted to know if this is something that can be improved by immer or i am tackling this problem wrong and should create every object as immerable or using produce?

**Comment by aleclarson** [comment]
Please provide some example code to better illustrate what you want versus the current behavior. Thanks!

**Comment by ivi-hamiti** [comment]
So taking the following example

```
const state = { propA: {}, propB: {}};
const mutated = produce(state, draft => {});
```
And supose propA is  a deeply nested property which is created prior to state initialization and as there are no changes to the state or properties propA will not be frozen. 

So i would expect that the produced state propA would have been frozen.

**Comment by mweststrate** [comment]
Freezing is a very expensive process. Only *changes* that are introduced in
producers are frozen. Which is just a dev utility to detect errors earlier
(it is automatically disabled in production, so you can't really rely on it
as well). The goal of immer is not to deepFreeze things. For a guaranteed
full freeze, just use packages that exist for that, such as deepfreeze.

Op ma 11 feb. 2019 om 08:26 schreef Ivi Hamiti <notifications@github.com>:

**Comment by chenhx2015** [comment]
I want to submit the same feature request too, then i found your discussion.  Are there any simple and 
 cheap way to meet the requirement? 
Current, i am using Object.freeze(a new object) in the produce function to ensure the Initial state immutable.

**Comment by aleclarson** [comment]
@chenhx2015 	See here: https://github.com/immerjs/immer/issues/260#issuecomment-443708874
