### ISSUE TITLE
Optimize array patches generating

### ISSUE THREAD

**Issue by ikabirov** [mweststrate/immer#319]
* [x] Issue: insert into array patches is not optimized
  * Version: 2.0.0
  * _SIMPLE_ Reproduction: https://codesandbox.io/s/543w79395x
  * Expected behavior:  patches contains one 'add' and one 'move' operation (https://tools.ietf.org/html/rfc6902#section-4.4)
  * Observed behavior: patches contains one 'add' operation and `array.length - index` 'replace' operations
  * [x] Occurs when using Proxies (use `setUseProxies(true)`)
  * [x] Occurs in the ES5 implementation (use `setUseProxies(false)`)

**Comment by ikabirov** [comment]
Same behavior with remove item, although it can use 'remove' operation (https://tools.ietf.org/html/rfc6902#section-4.2)

**Comment by mweststrate** [comment]
The patches are optimal from the generation perspective. So we generate
them as fast as possible. This isn't necessarily the minimal or best set of
patches. But that can in principle be solved by post processing the patches
if that is relevant for your use case. What patches are exactly generated
depends in principle on how the javascript engine implements them.

The patches are generated by observing how the runtime changes the
properties of the thing, not by intercepting the methods that are being
invoked. So apparantly the splice(0,0,0) is implemented by the engine as;
reassign the existing properties at all indicies, and create a new property
at index 3 at the end.

Another approach would be to intercept all the mutative operations on an
array, and generate patches ourselves based on the semantic meaning (Mobx
does that for example), but doing that would probably significantly
increase the size of the library. But maybe it's not that bad. Feel free to
take a stab at it. But note that the ES5 version has to produce the same
patches!)

**Comment by aleclarson** [comment]
Released in v2.1.0 🎉
