### ISSUE TITLE
Value Based Equality Checking

### ISSUE THREAD

**Issue by jclangst** [mweststrate/immer#324]
* [x] Feature request: ______
  * [x] I am willing to implement this myself

Really loving this library and the use of native javascript instead of having to fall back on ImmutableJS for structural sharing! One of the projects, I was originally using ImmutableJS for was for a compiler that runs isomorphically in the browser and in server environments. For performance reasons, there are a couple of key features that are necessary:

- structural sharing
- optimized value equality checks

Immer of course takes care of structural sharing (and is much better on the js engine due to not having to serialize and deserialize from native js like ImmutableJS requires). But the one thing that I am struggling with is value equality checks. This might not necessarily be an ideal feature to add to the core library, but I think it would be something that would benefit the immer ecosystem even if only as system on top of immer. I am willing to build such a system and make it available, but I was hoping for some initial feedback. 

Essentially, I'd like to take care of the following scenarios with relatively similar efficiency as ImmutableJS's `Collection.equals` (https://immutable-js.github.io/immutable-js/docs/#/Collection/equals):

Scenario 1: Same updates produce objects that appear equal

```javascript
const orig = { a: 1}
const new1 = produce(orig, draft => draft.a = 2);
const new2 = produce(orig, draft => draft.a = 2);
console.log(new1 === new2) //true
```

Scenario 2: Same compressed updates produce objects that appear equal

```javascript
const orig = { a: 1, b: "jane" }
const new1 = produce(orig, draft => {
  draft.a = 2;
  draft.a = 3;
  draft.b = "joe";
});
const new2 = produce(orig, draft => {
  draft.b = "joe";
  draft.a = 3;
});
console.log(new1 === new2) //true
```

Scenario 3: As a result of the above two, we are able to use the results of immutable operations as keys to one of the javascript `Map` implementations

```javascript
const orig = { a: 1}
const map = new WeakMap();

const new1 = produce(orig, draft => draft.a = 2);
const new2 = produce(orig, draft => draft.a = 2);

map.set(new1, "hi");
console.log(map.get(new2)) //"hi"
```

Note that for all of the above operations, I assume reference equality for value equality. This is only one possible route and I am open to other approaches. Another route (the one that ImmutableJS falls back on) is a combination of reference equality, hash equality (as a fail early mechanism), and structural recursion. I'd like to do no worse than what ImmutableJS provides in terms of efficiency, however.

I have spent a couple hours solutioning the problem, but haven't yet ended up at anything that provides an elegant solution. I wanted to put it out there to see if I am missing something obvious or if anyone else had any thoughts.

**Comment by jclangst** [comment]
Here is an architectural question that might yield a path a good solution:

Is the compress patches method mentioned here deterministic (https://medium.com/@david.b.edelstein/using-immer-to-compress-immer-patches-f382835b6c69)? 

To rephrase, if I am moving from states A -> B via some arbitrary mutations (i.e., multiple ways to move between those states), is there a way to compress those mutations into the same list of patches deterministically?

**Comment by mweststrate** [comment]
no, patches track mutations, they don't diff outcome. E.g. given base state
"x = { a: { b : 2 } }", the mutation "x.a = { c: 3 }", generates different
patches compared to "delete x.a.b; x.a.c = 3", although the end result is
structurally the same.

**Comment by jclangst** [comment]
Thanks for the clarification. Diffing wouldn't be the ideal of course because that would essentially be the same as a deep equality check which is what we'd like avoid. I am wondering if it would be possible to do some sort of just in time compression of the patches. For that, I think something might be reasonable performance wise IFF it didn't try to decompose something like the `x.a = { c: 3}` into the base primitive mutations. The architecture might be a JIT patch compressor module that could be used internally to generate deterministic patches per `produce` as well perhaps be used externally to compress patches from multiple `produce` calls (similar to the link above). Thoughts?

**Comment by mweststrate** [comment]
I think you've found yourself a very challenging problem, and my gut
feeling says that the costs in time / space might be higher than the
optimizations it enables in the end. That being said, you probably can get
quite far with a good hashing algorithm and some weakmaps, and if it
succeeds that would be really cool :)

**Comment by jclangst** [comment]
I would agree that that path seems dubious. If I were to develop a solution similar to the ImmutableJS one of assigning hash values to each subtree, do you think that would be better developed as something in the core library or something on top of the core library that interprets the patches and recomputes the hashes after `produce`?

**Comment by mweststrate** [comment]
I think that could be done on top, there are extension hooks to manipulate
the process of constructing the new tree

Op vr 8 mrt. 2019 16:02 schreef Jack Langston <notifications@github.com>:

**Comment by jclangst** [comment]
Thank you. I will look into it.

**Comment by luisherranz** [comment]
Hey guys, I'm looking into this as well.

I've found this library that seems to work well:
https://github.com/Starcounter-Jack/JSON-Patch

The actual algorithm that creates the patches don't seem too complex either:
https://github.com/Starcounter-Jack/JSON-Patch/blob/master/src/duplex.ts#L164-L216

I guess this can create some performance issues when dealing with large objects but the purpose of `immer` is to work near the leafs. I wonder how _bad_ this is in terms of performance.

Implementing something like this won't only make patches deterministic, but it will minimize re-renders in React when users do things like:
```js
const state = { user: { name: "Jon", surmane: "Snow" } };

const Name = ({ name }) => <div>Name: {name}</div>;
const Surname = ({ surname }) => <div>Surname: {surname}</div>;

// Right now in immer these are different:
state.user.surname = "Targaryen";
// patch -> { op: 'replace', path: '/user/surname', value: 'Targaryen' }
// rerenders -> Only "Surname"
state.user = { name: "Jon", surname: "Targaryen" };
// patch -> { op: 'replace', path: '/user', value: { name: "Jon", surname: "Targaryen" } }
// rerenders -> Both "Name" and "Surname"
```

Using `JSON-Patch` to minimize the patches, they are equivalent:
```js
state.user.surname = "Targaryen";
// patch -> { op: 'replace', path: '/user/surname', value: 'Targaryen' }
// rerenders -> Only "Surname"
state.user = { name: "Jon", surname: "Targaryen" };
// patch -> { op: 'replace', path: '/user/surname', value: 'Targaryen' }
// rerenders -> Only "Surname"
```

Actually, MobxStateTree works that way:
```js
const store = types
  .model({
    user: types.model({
      name: types.string,
      surname: types.string
    })
  })
  .actions(self => ({
    changeSurname(surname) {
      self.user.surname = surname;
    },
    changeUser(user) {
      self.user = user;
    }
  }))
  .create({ user: { name: "Jon", surname: "Snow" } });

store.changeSurname("Targaryen");
// patch -> { op: 'replace', path: '/user/surname', value: 'Targaryen' }
store.changeUser({ name: "Jon", surname: "Targaryen" });
// patch -> { op: 'replace', path: '/user/surname', value: 'Targaryen' }
```

I know developers can be educated to modify leafs instead of nodes, but `immer` is about improving the developer experience, isn't it?

What do you think @mweststrate?

**Comment by luisherranz** [comment]
Another idea: what if, instead of comparing the values to get the patches, it iterates over the received object and adds the leaves one by one:

```js
state.user = { name: "Jon", surname: "Targaryen" };
// This triggers a "set" with:
target = state
prop = "user"
value = { name: "Jon", surname: "Targaryen" };

// And runs something like:
for (let key in value) {
  target[prop][key] = value[key]
}
```

This can happen only if there is an existing object in `state.user`. If it's not, it just adds it.

**Comment by mweststrate** [comment]
Please open a new issue @luisherranz, that way others can see it :)

Short answer: for what you want Immer would do do start diffing, which is precisely what it tries to avoid. The patches now reflect the mutation that were made. There are many different ways on what 'the most optimal' patch is. Many small ones? Or better one big one? The "best" largely depends on your use case. So immer opts for "the most efficient" to generate. From there you can post-process the patches in your own code to get your preferred kind of patch. For example by taking an object assignment patch, and it's inverse patch, the combination of those two will enable you to do diffing and achieve your leaf-patches.

**Comment by luisherranz** [comment]
You're right, it's not clear which one is the best and also the dev can process a post-process the patch so no need for a new issue :)
