### ISSUE TITLE
ES5 implementation fails when reassigning property value after deleting

### ISSUE THREAD

**Issue by ikabirov** [mweststrate/immer#328]
* Version: 2.1.0
  * _SIMPLE_ Reproduction: `state = immer.produce({a:1}, draft => {delete draft.a;draft.a = 2})`
  * Expected behavior: `state.a == 2`
  * Observed behavior: `state.a == 1`
  * [ ] Occurs when using Proxies (use `setUseProxies(true)`)
  * [x] Occurs in the ES5 implementation (use `setUseProxies(false)`)

**Comment by aleclarson** [comment]
Nice catch! Looking into it. 👍
