### ISSUE TITLE
react native can not recognize `.mjs` file

### ISSUE THREAD

**Issue by sunnylqm** [mweststrate/immer#331]
error: bundling failed: Error: While trying to resolve module `immer` from file `/Users/.../src/reducers/uiStateReducer.ts`, the package `/Users/.../node_modules/immer/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/.../node_modules/immer/dist/immer.mjs`.

Related to https://github.com/mweststrate/immer/commit/b9f0029bf77a7ab993133551a635680b559c7532#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by mohsinulhaq** [comment]
![image](https://user-images.githubusercontent.com/7688231/54258615-2f6cb400-4589-11e9-9f86-f1c31901fc11.png)
Is the fix going to address this issue as well? @egoist

**Comment by egoist** [comment]
@mohsinulhaq probably, you can rename your `node_modules/immer/dist/immer.mjs` to `immer.module.js` and update the `react-native` field in its `node_modules/immer/package.json` accordingly to see if it works.

**Comment by mohsinulhaq** [comment]
I have since pinned immer version to 2.1.1 and everything is fine

**Comment by nhchuongchkst19** [comment]
This error reappears at version 10.0.2

**Comment by aardvarkk** [comment]
Confirm v10 seems to break React Native compatibility (at least for me on RN v0.63.5). Downgrading to v9 fixed the problem for me.
