### ISSUE TITLE
Property drilling on empty object

### ISSUE THREAD

**Issue by pie6k** [mweststrate/immer#337]
## 🚀 Feature Proposal

It would make it possible to do something like this

```js
const result = produce({}, (draft) => {draft.foo.bar.baz = 2})
```

where `result` would be 

```js
{
  foo: {
    bar: {
      baz: 2
    }
  }
```

## Motivation

It would allow creating desired objects from empty objects without boilerplate.

**Comment by mweststrate** [comment]
There are packages that already support this (`nevernull` from the top of
my head).

It should not be part of Immer imho for several reasons:
1. It doesn't fit the philosophy where we leverage existing mutable
javascript constructs to create immutable objects
2. This wouldn't be polyfillable to ES5
3. This is not the problem immer tries to solve, and could just as well
solved by another package. making it available by default in produce would
be a matter of simple comisition from there.
