### ISSUE TITLE
immerable symbol samples

### ISSUE THREAD

**Issue by kofifus** [mweststrate/immer#341]
From the readme "Supported object types - Only plain objects and arrays are automatically drafted by Immer. This means other object types should never be mutated unless you added the exported immerable symbol to the object itself, its prototype, or its class constructor. In that case, the object is essentially an immutable plain object with a custom prototype."

It would be helpful for the readme to have a sample of how this  immerable symbol is used, ideally in all the 3 cases above (the object itself, its prototype, or its class constructor)

Thanks!

**Comment by aleclarson** [comment]
I've just improved (hopefully) the section you mentioned. With some examples! 👍 

PS: I decided to omit `prototype` support from the docs, since it's never necessary or the best option.

**Comment by sladiri** [comment]
For me the implications of the `immerable` marker was not clear from the Readme. Maybe link to https://github.com/immerjs/immer/issues/357 ?

**Comment by mweststrate** [comment]
PR welcome

Op zo 11 aug. 2019 10:27 schreef Slađan Ristić <notifications@github.com>:
