### ISSUE TITLE
Assigning a sub-reducer result to a property mutates original state

### ISSUE THREAD

**Issue by renchap** [mweststrate/immer#343]
## 🐛 Bug Report

First of all, thanks for Immer!

I am using a main Redux state with child-states, each with its own reducer. For some actions I need the main reducer to update the whole state (for example initialisation from server data).

```ts
const subtreeReducer = produce((subtreeDraft, action) => { … }

const rootReducer = produce((draft, action) => {
  switch (action.type) {
    case "INIT_FROM_SERVER":
      return …
      break

    default:
     draft.subtree = subtreeReducer(draft.subtree, action)
  }
}, {)
```

I think I understand why this is not working (reassigning a whole property, not changing it), but I am not finding the proper "immer" way to do so, and I think this is a quite common usecase.

## Link to repro (highly encouraged)

See Codesandbox: https://codesandbox.io/s/olo1yo9y3z

## To Reproduce

See codesandbox

## Expected behavior

I would expect the same result with a sub-reducer and without it. But when I am using my sub-reducer, the original state is mutated.
I guess the proper solution would be for the sub-reducer to not call `produce`, but it makes this reducer harder to test.

## Environment

-   **Immer version:** 2.1.4
-   [x] Occurs with `setUseProxies(true)`
-   [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by renchap** [comment]
Note: The codesansbox is like this as I tried to reproduce a problem I am seeing in my app.

I just tested to remove the `splice` call it my reducer and the problem goes away. So I am really unsure of what is really happening here 🤔

**Comment by aleclarson** [comment]
It's an internal bug. Looking into it. 👍

**Comment by renchap** [comment]
Thanks, that was quick!
So this was not me doing anything wrong, good to know 😄
