### ISSUE TITLE
Problem with Draft type on generic keyof Property

### ISSUE THREAD

**Issue by phryneas** [mweststrate/immer#345]
## 🐛 Bug Report

When a state value is a `keyof` a generic (unknown) type, I'm getting 
```
Type 'keyof T' is not assignable to type 'Draft<keyof T>'.
  Type 'string | number | symbol' is not assignable to type 'Draft<keyof T>'.
    Type 'string' is not assignable to type 'Draft<keyof T>'.ts(2322)
```

## Link to repro

See this CodeSandbox: https://codesandbox.io/s/mj9vk83kjj

## Environment

-   immer Version 1 and 2 seem to be affected

**Comment by aleclarson** [comment]
This is currently a limitation of TypeScript.

When you wrap a generic parameter with a conditional type, assignability is lost.
