### ISSUE TITLE
how to read the performance chart

### ISSUE THREAD

**Issue by epikhighs** [mweststrate/immer#45]
Do higher numbers mean better performance?

https://github.com/mweststrate/immer#performance

Thanks.

**Comment by mweststrate** [comment]
No worse. Numbers are milliseconds

**Comment by epikhighs** [comment]
wow that's pretty nice performance for immer -  i've been looking for an alternative to immutable.js that just works with existing JS objects and has the nice performance characteristics.

Are you using this in production?

**Comment by mweststrate** [comment]
Nope, nor will I soon I think, as I don't have any active Redux / immutability based project app. Probably others are, or are soon. (the project is only 2 weeks old)

**Comment by Izhaki** [comment]
@epikhighs Note that in https://github.com/immerjs/immer#performance the text says:

> This test takes 50,000 todo items

That's 50K, whereas in the image it says 500K:

![image](https://user-images.githubusercontent.com/880132/62980308-1ad56600-be1e-11e9-81cd-637672389145.png)

As the [code](https://github.com/immerjs/immer/blob/master/__performance_tests__/todo.js#L15) shows, 50K is the right figure (image's wrong):

```
const MAX = 50000
```

**Comment by mweststrate** [comment]
Please refrain from commenting on closed issues, as typically no one will notice the comment. Please just open a new one
