### ISSUE TITLE
support NODE_ENV='production'  substitution to turn of auto-freeze

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/immer#46]

**Comment by Gregjarvez** [comment]
@mweststrate I want to give this one a shot tonight if I get time. 
So basically make sure auto Freeze is off when the code builds in production mode irrespective of it being specified in the code as on?

**Comment by mweststrate** [comment]
node, the otherway around; in the source code the variable now defaults to
'true', but it should default to `autoFreeze = process.env.NODE_ENV !==
"production"`  and further respect any `setAutoFreeze` call. I'm not sure
what the nicest way is to set this up, but you can look at the React or
mobx-state-tree repo's for inspiration. If it requires setting up a bundler
that is fine (preferrably rollup). Thanks in advance!

Op di 9 jan. 2018 om 14:37 schreef Gregory Assasie <notifications@github.com

**Comment by Gregjarvez** [comment]
@mweststrate oh okay. I will take a look at that tonight

**Comment by mweststrate** [comment]
Reopened for now, not entirely sure #64 addresses it, and implementation doesn't take it into account yet at least

**Comment by arthurdenner** [comment]
I'm not sure if I understood correctly what is this issue about, but (if I did) my suggestion would be to use [this plugin](https://github.com/rollup/rollup-plugin-replace). It needs to go in the plugins list as something like this in `rollup.config.js`:

```javascript
plugins: [
//  ...
  replace({
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
  })
]
```
and in `common.js` you do something like this:
```javascript
export let autoFreeze = process.env.NODE_ENV !== 'production'
```

I took a look at the mobx-state-tree repo and they do [this](https://github.com/mobxjs/mobx-state-tree/blob/7fa28191aeb75e1f51c8e13654641508452ffbe9/packages/mobx-state-tree/rollup.config.js#L6), but I guess the idea is the same?

Is that the desirable behaviour or did I miss the point entirely? 😸

**Comment by mweststrate** [comment]
Honestly I don't know myself exactly 😊. But the goal is that autofreeze is
by default enabled, unless the hosting app is bundling a production build.

Op di 16 jan. 2018 22:13 schreef Arthur Denner <notifications@github.com>:

**Comment by Gregjarvez** [comment]
@mweststrate Hi. been gone for a while. 
here is my take on this.I pretty much used `process.env.NODE_ENV` but I used the fact that the code is minified as a fallback to when process.env.NODE_ENV is undefined . I mean undefined sure is a falsy value too. Probably unnecessary but i thought it would be useful for cdn users and stuff

```javascript 
function verifyMinified () {}

const env = process.env.NODE_ENV;
const shouldFreeze = env  ? !(env === 'production') : verifyMinified.name === 'verifyMinified'

export let autoFreeze = shouldFreeze
```
