### ISSUE TITLE
ES5 is no longer ES5

### ISSUE THREAD

**Issue by atrocious** [mweststrate/immer#51]
After the 'immer -> produce' change, produce uses classes and arrow functions in the es5 build, causing IE11 to have a fit :)

**Comment by mweststrate** [comment]
argh good point. Yep, need to transpile now :'(

Op wo 10 jan. 2018 om 12:25 schreef atrocious <notifications@github.com>:

**Comment by mweststrate** [comment]
Will fix tonight

**Comment by mweststrate** [comment]
should be fixed in 0.5, could you verify?

**Comment by atrocious** [comment]
Yeah it works now. :D Thanks for creating this, I love immer!
