### ISSUE TITLE
Cannot minify immer.js in create-react-app

### ISSUE THREAD

**Issue by Teyras** [mweststrate/immer#52]
The title says it all, basically. When I tried to create an optimized production build of a project that uses immer with `create-react-app`, I got told that `immer.js` cannot be minified. I believe this is because you do not terminate your statements with semicolons - the first error was on line 10. Is there anything that can be done about this?

**Comment by mweststrate** [comment]
@Teyras could you retry with 0.6.0? The versions before that optimized the default output for modern browsers. I just made ES5 the default target

**Comment by arthurdenner** [comment]
@mweststrate, I've tested and it is working fine with 0.6.0 or above. Thanks for fixing it.

**Comment by mweststrate** [comment]
Fixed in 0.6
