### ISSUE TITLE
TypeError: Cannot perform 'get' on a proxy that has been revoked

### ISSUE THREAD

**Issue by hex13** [mweststrate/immer#53]
Node: 8.4.0
immer: 0.5.0

```javascript
const produce = require('immer').default;
const result = produce(
    {arr: [{count:1}, {count: 2}, {count: 3}]},
    draft => {
        draft.arr = draft.arr.filter(item => item.count > 2);
    }
);

console.log(result); // throws

```
`result.arr[0].count` seems to be troublesome, even referencing to this variable throws an error. 

Result of function `produce` should be a plain JS object, right? Because it seems that the result sometimes contains proxies inside.

**Comment by zhw2590582** [comment]
I think the bug is here.

https://github.com/mweststrate/immer/blob/553b6cefb4e6bdaae455663fa6a15f857d4c8d93/src/immer.js#L196

I think you missed something like this. right?
```js
    function finalize(base) {
        let state;
        if(Array.isArray(base) && isProxy(base[0])){
            state = base[0][PROXY_STATE]
        } else if(isProxy(base)) {
            state = base[PROXY_STATE]
        } else {
            return base
        }
        if (state.modified === true) {
            if (Array.isArray(state.base)) return finalizeArray(state)
            return finalizeObject(state)
        } else return state.base
    }
```

**Comment by zhw2590582** [comment]
```js
function finalize(base) {
    // console.log(base, isProxy(base))
    if (isProxy(base)) {
       // ...
    }
    return base
}
```
In this case, `finalize` function is executed twice.
If `base` is a proxy object, `isProxy(base)` is true.
```js
State { arr: [ State { count: 3 } ] }
```
If `base` is a proxy array, `isProxy(base)` is false, and return a proxy.
```js
[ State { count: 3 } ]
```
I think you should first determine the type of object, as before, right?
```js
function finalize(base) {
   if (isPlainObject(base)) return finalizeObject(base)
   if (Array.isArray(base)) return finalizeArray(base)
   return base
}
```

**Comment by mweststrate** [comment]
Bug confirmed, fix WIP

**Comment by mweststrate** [comment]
Fixed in 0.6.1

**Comment by nickmccurdy** [comment]
I think I found a regression in 1.1.1, but it's working again in 1.1.3.

**Comment by kikill95** [comment]
I've reproduced this issue in 1.7.1

**Comment by mweststrate** [comment]
@kikill95 cool. Please open a new issue with reproduction. Responding to closed issues is generally pointless :).
