### ISSUE TITLE
Does not seem to support changing the root object type.

### ISSUE THREAD

**Issue by zhw2590582** [mweststrate/immer#54]
Consider adding some warnings for this?

```js
const produce = require('immer').default;

const result1 = produce([], draft => {
    draft = {}
})
console.log(result1) // []

const result2 = produce({}, draft => {
    draft = []
})
console.log(result2) // {}
```

**Comment by mweststrate** [comment]
@zhw2590582 your example doesn't modify the draft object, it just changes the _reference_ to the draft.

Compare:
```javascript
function produce(thing) {
   thing = [ 3 ]
   console.log(thing)
}

const draft = { x: 1}
produce(draft)
console.log(draft)
```
This will print `[3]` first, but in the end still `{x: 3}`. You reassigned the variable called `thing`, but didn't actually change the thing `thing`  was pointing to.

Most language properly protect against this. But in the JavaScript case; setting up proper linting should protect you against these kind of mistakes

**Comment by mweststrate** [comment]
See https://eslint.org/docs/rules/no-param-reassign
