### ISSUE TITLE
create smaller standard built

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/immer#58]
Currently < 3KB, but, could be smaller by

1. using rollup
2. share common pieces of functionality between es5 and immer.js implementation
3. make the classes methodless

**Comment by arthurdenner** [comment]
Hi, @mweststrate.

What about using [microbundle](https://github.com/developit/microbundle)? It's powered by rollup and seems to do everything you want with only one command. I tested and this was the output:

![image](https://user-images.githubusercontent.com/13774309/34907076-bf40185e-f857-11e7-92d5-615101c2335b.png)

If you think this result is good enough, I can open a PR to add it.

**Comment by mweststrate** [comment]
That looks convenient! Feel free to PR. Will it uglify the umd build?

Op za 13 jan. 2018 om 15:54 schreef Arthur Denner <notifications@github.com

**Comment by arthurdenner** [comment]
Yes, it compress the output using UglifyJS by default, but I'm not sure if it fulfills your needs, so I'm going to open a PR so you can analyze it.

**Comment by mweststrate** [comment]
Released as 0.8.0. Thanks @arthurdenner!

**Comment by arthurdenner** [comment]
Thanks for the opportunity to contribute and learn something new. :)
