### ISSUE TITLE
minified version

### ISSUE THREAD

**Issue by pandanoir** [mweststrate/immer#60]
I want to use minified file, but now immer doesn't have a minified version.

**Comment by mweststrate** [comment]
Umd?

Op za 13 jan. 2018 09:11 schreef Naoto Ikuno <notifications@github.com>:

**Comment by pandanoir** [comment]
yes.
https://unpkg.com/immer/dist/immer.umd.js
This CDN file isn't minified. Many libraries, such as jQuery, lodash and riot.js, provide minified files.

**Comment by MartinKolarik** [comment]
You can use [jsDelivr CDN](https://www.jsdelivr.com/), it supports on-demand minification of any file: https://cdn.jsdelivr.net/npm/immer/dist/immer.umd.min.js

**Comment by mweststrate** [comment]
That is freaking small

Op za 13 jan. 2018 om 13:40 schreef Martin Kolárik <notifications@github.com

**Comment by pandanoir** [comment]
I didn't know that jsDelivr CDN automatically minify and provide a JS file. Thank you!
