### ISSUE TITLE
Support with Typescript?

### ISSUE THREAD

**Issue by sharmad-nachnolkar** [mweststrate/immer#61]
Hi,

I am using typescript in my project. If Immer just uses native JS objects then it means that TS suggestions and compile errors should work right?

**Comment by mweststrate** [comment]
Yes. Typescript typings are included in the package, so you shouldn't need
to setup anything when importing the module in a TS project

Op za 13 jan. 2018 om 10:11 schreef sharmad-nachnolkar <
notifications@github.com>:

**Comment by sharmad-nachnolkar** [comment]
Thanks for the quick reply. I am working on a new project and had started using Immutable.js but its set and get api don't provide the type checks with typescript. I am going to try and switch to Immer. Thanks!
