### ISSUE TITLE
Support null-soaking on the draft state?

### ISSUE THREAD

**Issue by joshwcomeau** [mweststrate/immer#62]
One of the major pain points when dealing with nested data in Javascript is not having a "null soak" (AKA existential) operator.

Coffeescript has a built-in one:

```coffee
obj = { a: { b: 5 }}

# logs `5`
console.log obj.a?.b

# logs `undefined`
console.log obj.foo?.bar?.b
```

Immutable.js offers a similar pattern with [getIn](https://facebook.github.io/immutable-js/docs/#/getIn), albeit with a really-not-great API:

```js
import { getIn } from 'immutable';

getIn({ x: { y: { z: 123 }}}, ['x', 'y', 'z']) // 123
getIn({ x: { y: { z: 123 }}}, ['x', 'q', 'p']) // undefined
```

I wonder if it would be possible/feasible to add such a solution for the `draftState` object in Immer? I imagine it'd be really nice to be able to do stuff like:

```js
import produce from 'immer';

const initialState = { a: { b: 5 } }

const nextState = produce(initialState, (draftState) => {
  const {baz} = draftState.foo.bar;

  if (typeof baz === 'undefined') {
    someMutativeMethodToCreateBaz(draftState);
  }
})
```

With proxies, this is possible. A package called [`safe-proxy`](https://github.com/erictrinh/safe-proxy) implements this. However I don't think an ES5 alternative would be doable (maybe with a try/catch or some really gross function.toString business?).

If this project is committed to maintaining an identical API with the ES5 version, it's probably more trouble than it's worth, unless I'm missing something?

Happy to contribute some work towards this idea because I think it could be a really neat addition, but yeah I also wouldn't be surprised if it's simply not worth doing :) mostly just wanted to start a discussion about it.

EDIT: actually, now that I think about it... having the API be totally implicit like that feels like a bad idea, since users who aren't familiar with Immer would believe that it's a native feature of the language. Could be really misleading.

We could export a helper that does it (like `safe-proxy` does), but really the user can just bring their own helper if they want to be able to do that.

**Comment by joshwcomeau** [comment]
Gonna close the issue, since I no longer think this is a worthwhile thing to add, but feel free to reopen if anyone thinks there's more discussion to be had here!

**Comment by hex13** [comment]
I think `get` from lodash could be used for such thing

```javascript
var o = {a: {b: 3}}
const  ld = require('lodash');
ld.get(o, ['a', 'b']);   // 3
ld.get(o, ['a', 'b', 'nonexisting', 'blah']);   // safely returns undefined 
```
