### ISSUE TITLE
Change source code to TypeScript

### ISSUE THREAD

**Issue by styfle** [mweststrate/immer#67]
I noticed you have the typescript devDependency but the [source code](https://github.com/mweststrate/immer/blob/master/src/index.js) is written in JS.
Any reason why you didn't write it in TS?

**Comment by mweststrate** [comment]
None other than that it started out really tiny and I initially only
targeted recent Node versions

Op di 16 jan. 2018 om 19:18 schreef Steven <notifications@github.com>:

**Comment by styfle** [comment]
Ok maybe if I have time, I'll write a PR to convert to TypeScript 😃

**Comment by mweststrate** [comment]
Such change is welcome, but ping me beforehand (or wait a few days). I am
currently shoving a lot of code around to improve code reuse / build

Op di 16 jan. 2018 om 19:35 schreef Steven <notifications@github.com>:

**Comment by sebasgarcep** [comment]
Seeing as how TS is oriented towards OO code and Flow towards FP code, wouldn't it make more sense to add Flow typings instead?

**Comment by styfle** [comment]
> Seeing as how TS is oriented towards OO code and Flow towards FP code, wouldn't it make more sense to add Flow typings instead?

What makes you say that? TypeScript works great for FP code and I haven't run into anything it couldn't do.

**Comment by mweststrate** [comment]
That sounds like a weird distinction to make between the two. But yes there
is an open issue to add flow typings, just didn't get to that yet :)

Op wo 17 jan. 2018 om 20:42 schreef Sebastian Garrido <
notifications@github.com>:

**Comment by sebasgarcep** [comment]
@styfle I don't doubt TS capabilities, I've used it before and it is great, but Flow brings a different set of guarantees and capabilities. I just thought the author might want to check it out before deciding on which option suits this project better.

**Comment by mweststrate** [comment]
Ok, the code base should be pretty stable now. PR is welcome

**Comment by Gregjarvez** [comment]
@mweststrate I am fairly new to typescript but I think this would an opportunity to get my hands dirty. with assistance, I would like to take this on?

**Comment by mweststrate** [comment]
@Gregjarvez sure, feel free to submit a PR :)

**Comment by pqkluan** [comment]
JS support both OOP and FP. Why we have to focus on single perspective to decide the support the static types checker?

[Here is the comparison between Typescript and Flow](https://github.com/niieani/typescript-vs-flowtype).

IMHO, Typescript is more stable in term of performance (my experience with IntelliSense on vs-code), better syntax, and supported by many large projects. Plus, we could support TypeScript type definitions in a seperate package if needed.

**Comment by urish** [comment]
@mweststrate do you know if anybody is working on this?

If not, please leave a comment at urish/typewiz#35 and I'd love to do this for you.

**Comment by mweststrate** [comment]
@urish PR welcome (doesn't seem anybody is working on it) :)

**Comment by urish** [comment]
@mweststrate excellent, I saw your comment. I will be working on the PR tomorrow. Fun ahead!

**Comment by urish** [comment]
See #128 - basically, all the TS setup is there (code is TS, builds and tests pass), though I haven't added any new type annotations yet (except for few fixes to make the code compile).

**Comment by mweststrate** [comment]
Closing for now, could be reopened if somebody feels for it :)
