### ISSUE TITLE
Support with redux-actions handleActions({})

### ISSUE THREAD

**Issue by sharmad-nachnolkar** [mweststrate/immer#74]
@mweststrate - Can I use produce on my reducer with redux-action's handleActions(Object) method?

eg -
```
const reducer = (state = initState, action) => produce(state, draft => 
	handleActions({
			[ACTION_TYPES.FETCH_DATA]: (draft, action) => {
				draft.data = action.payload
			}
     })
)
```

**Comment by mweststrate** [comment]
Try it?

Op do 18 jan. 2018 16:06 schreef sharmad-nachnolkar <
notifications@github.com>:

**Comment by sharmad-nachnolkar** [comment]
Tried but doesn't seem to work. Will try to dig more into the issue.

**Comment by mweststrate** [comment]
I skimmed the `handleActions` docs quickly, but from that I guess (!) there are 2 problems with your approach:

1. handleAction requires two params
2. handleActions creates a reducers, while your `reducer` const _is_ a reducer. So you now have written a reducer, that, when called, just creates a new reducers, but it never invokes it or does anything with it. It's like creating a function but never actually calling it. 

So I guess something like the following will work better

```
const reducer = produce((draft, action) => 
	handleActions({
			[ACTION_TYPES.FETCH_DATA]: (draft, action) => {
				draft.data = action.payload
			}
     }, initState)(draft, action)
})
```

However, if you ask me, that is still ugly, as every time you run the reducer, you are creating a _new_ reducer, invoke it once and loose it again. So I thin the following is neater:

```
const reducer = handleActions({
    [ACTION_TYPES.FETCH_DATA]: produce((draft, action) => {
        draft.data = action.payload
    })
}, initState)
```

But as said, I just skimmed the docs, so I might be completely missing what `handleActions` actually does

**Comment by mweststrate** [comment]
Closing as question seems answered

**Comment by mweststrate** [comment]
@ronen don't comment on closed issues, chances are 50-50 that someone will see it.

**Comment by mweststrate** [comment]
@ronen anyway, check https://gist.github.com/kitze/fb65f527803a93fb2803ce79a792fff8 or some of the other stuff linked here: https://github.com/mweststrate/immer#cool-things-built-with-immer
