### ISSUE TITLE
Cannot find variable Symbol in react native

### ISSUE THREAD

**Issue by anish000kumar** [mweststrate/immer#75]
I have been using immer with react-native , it runs fine on ios but on android it throws error 'Cannot find variable Symbol in react native'.

**Comment by Sigmus** [comment]
A polyfill may help: https://github.com/medikoo/es6-symbol

**Comment by mweststrate** [comment]
Should be fixed in 0.8.3, could you verify, @anish000kumar ?

**Comment by anish000kumar** [comment]
@mweststrate  works like charm! thanks!
