### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by anish000kumar** [mweststrate/immer#77]
![image](https://user-images.githubusercontent.com/9535166/35165913-0bec8822-fd76-11e7-9b55-f1394238ad33.png)

Getting this issue in a react-native project on android only. on iOS the app runs fine
immer@0.8.3

**Comment by mweststrate** [comment]
Argh yes, RN on android polyfills nothing. As quick fix: make sure you polyfill Object.is, will probably include a polyfill in the package soon

**Comment by mweststrate** [comment]
Added polyfill in the package, should be fixed by 0.8.4. Please reopen if this isn't the case. I think everything the package uses is now polyfilled on old javascript engines

**Comment by anish000kumar** [comment]
@mweststrate thanks! Everything works well now, on ios as well as android!
