### ISSUE TITLE
Create es5 compatible version

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/immer#8]
If there is enough interest. 

Proxy using defineProperty (the mobx way), use faux arrays and dirty check for key additions

**Comment by mattiamanzati** [comment]
I was thinking about a compiler-wise option, something like a babel (or TS) plugin transformer that looks for immer() calls, and add calls to a function to report which parts of draftState may have changed, and then just compare them instead of the whole state

**Comment by mweststrate** [comment]
I think this problem is relatively easily solvable . Gonna try tonight

**Comment by mweststrate** [comment]
Yes, it is solvable :) Implementation is basically ready but needs merging into the original impl (with code reuse, now just copy pasted the base file), see #22

**Comment by mweststrate** [comment]
Released! As 0.2.0. Faux arrays weren't needed, so object / array semantics remain true :)
