### ISSUE TITLE
Issue while trying to use map, filter , find etc

### ISSUE THREAD

**Issue by anish000kumar** [mweststrate/immer#84]
I am trying out immer for a simple todos app. I have a simple reducer function like this -

```
Reducer( state = initialState, action) {
   let method = actionList[action.type];
        if(method){
		const nextState = produce(state, draft_state => {
			let new_state =  method( draft_state , action);
			return new_state
		})
		return nextState;
	}
	else return state
}

```

`actionList` is an object which functions as a clutter free version of typical reducer (using the above function in the hindsight):

```
const actionList = {
    ADD_TODO : (state, action) => state.push(action.todo),
    TOGGLE_TODO : (state, {todo}) => {
       return state.map( _todo =>{
           if( _todo.id==todo.id){
             _todo.completed = !_todo.completed
           }
        });
    }
}
```

`state` object goes like this:

```
const state =  [
        {
            id :1,
            text: 'sample todo',
            completed : true
        }
   ]
```

The issue is I am unable to get `TOGGLE_TODO` to work using this approach (or any approach). To put it simply, how may I toggle the completed flag of a todo using below method:

```
TOGGLE_TODO : (state, {todo}) => {
      // here state is the proxy of currentState generated by immer, todo is the todo object to be toggled
    }
```

here's sandbox link if that helps better:
https://codesandbox.io/s/ymw0127r39

**Comment by zcei** [comment]
In the codesandbox snippet it looks like you're missing out an underscore in line 22. You have to mutate `_todo` in order to get the change recorded.

Also, because of direct mutation, one should use `forEach`, as you're not returning something, `draft` will only contain null elements, so you wouldn't be able to further modify them.

**Comment by anish000kumar** [comment]
Got the issue resolved! @zcei  thanks!
