### ISSUE TITLE
Works fine in react-native with iOS, but fails to work with Android

### ISSUE THREAD

**Issue by james-srl** [mweststrate/immer#92]
I get the following error whenever I try to use Immer in react-native on Android: 

undefined is not a function (evaluating 'Object.is(maybeVoidReturn, undefined)')

the error happens in es5.js line 237

Any insight into this issue would be greatly appreciated!

**Comment by benbraou** [comment]
@james-srl this seems to be a dup of https://github.com/mweststrate/immer/issues/77 .
Please update to the latest version of `immer`. I guess you are using a version `<=0.8.3`
Please feel free to reopen an issue if you still reproduce with the latest version.

**Comment by james-srl** [comment]
You were right! I should have dug more into the issues before posting this. Thank you! Immer is awesome.

**Comment by mweststrate** [comment]
In any case always make sure to only report issues based on the latest
version of a package ;-)

Op wo 7 feb. 2018 om 05:05 schreef James <notifications@github.com>:
