### ISSUE TITLE
Wrong expression to detect production mode

### ISSUE THREAD

**Issue by jkordas** [mweststrate/immer#95]
In expression:

`const inProduction = (typeof process !== "undefined" && process.env.NODE_ENV === "production") ||
        verifyMinified.name === "verifyMinified"`

Second condition:

`verifyMinified.name === "verifyMinified"`

is inappropriate.

It should probably be `verifyMinified.name !== "verifyMinified"` if I understand correctly ('===' changed to '!==').

**Comment by mweststrate** [comment]
Fixed in 1.0.3. Thanks for noticing!
