### ISSUE TITLE
unexpected result with typescript class

### ISSUE THREAD

**Issue by dubiousandrew** [mweststrate/immer#96]
When I try to modify a property of a typescript class, the producer modifies the state but doesn't return a new state.

Here is a simple typescript example:
```
import produce from 'immer';

class Simple {
  title: string;
}

var state = {
  S: new Simple()
}

console.log(state); //outputs: { S: Simple {} }

var newstate = produce(state, draft => {
  draft.S.title = 'newval';
})

console.log(newstate === state);//outputs: true, should be false
console.log(newstate);//outputs: { S: Simple { title: 'newval' } }
```

is there any chance that this will be addressed?  I think perhaps there should at least be a more explicit warning to not do this in the readme.

**Comment by mweststrate** [comment]
See https://github.com/mweststrate/immer#pitfalls. Because there is now generic `clone` mechanism for arbitrarily complex types, immer cannot produce a new state for you from your class without opening a potential can of worms.

**Comment by mweststrate** [comment]
If you did read that, but if it wasn't clear, feel free to PR improvements on the docs :)

**Comment by sobkulir** [comment]
I just spent ~3 hours debugging a similar piece of code. I didn't find it mentioned in the docs. Can you please mention it more explicitly, i.e. "Immer can't handle custom classes. (example)"? 

I had quite complex state, but it basically boils down to this.
```ts
import { produce } from "immer";

class ArrayWrapper {
  constructor(readonly letters: number[]) {}
}

const state = new ArrayWrapper([1]);

interface State {
  letters: number[];
}

const newState = produce(state, (draft: State) => {
  draft.letters.pop();
});

// True
console.log(state === newState);
```

**Comment by mweststrate** [comment]
https://immerjs.github.io/immer/docs/complex-objects

Feel free to PR clarifications to make things more explicit.

Op za 2 nov. 2019 20:05 schreef Roman Sobkuliak <notifications@github.com>:

**Comment by MPanahandeh** [comment]
@mweststrate I like to introduce my implementation

`export interface Clonable<T> {
	clone(): T;
}
/**
 * checks if the argument has implemented Clonable interface
 * @param arg
 */
const canClone = (arg: any): arg is Clonable<any> => {
	return arg && (arg as Clonable<any>).clone !== undefined;
};

class ImmerClass {

	 * @param {any} model - the initial state
	 * @param {Function} producer - function that receives a proxy of the base state as
	 * first argument and which can be freely modified
	 * @returns {any} a new state, or the initial state if nothing was modified
	 */
	produce<T>(model: T, producer?: (draft: T) => void): T {
		let clonedModel: any = model;

		if (canClone(model)) clonedModel = (model as any).clone();

		Object.entries(clonedModel).forEach((entry) => {
			const prop: any = entry[0];
			const modelValue = entry[1];
			if (modelValue instanceof Array) {
				clonedModel[prop] = modelValue.map((m) => produce(m));
			} else {
				if (canClone(modelValue)) {
					clonedModel[prop] = produce(modelValue, (draft: any) => draft);
				}
			}
		});

		if (producer) producer(clonedModel);
		return clonedModel as T;
	}
}

const immerClass = new ImmerClass();
const produce = immerClass.produce;

export default immerClass;
export { produce };
`
============
the test class
========

import { Cloned } from '../../pages/Interfaces';
import { Clonable, produce } from '../Immer.class';

describe('ImmerClass', () => {
	let originalStudent: Student;
	class Semester implements Clonable<Semester> {
		courses: Course[];
		constructor(me?: Cloned<Semester>) {
			this.courses = me?.courses ?? [];
		}
		clone(): Semester {
			return new Semester({ ...this });
		}
	}
	class Course implements Clonable<Course> {
		courseName: string;
		constructor(me?: Cloned<Course>) {
			this.courseName = me?.courseName ?? '';
		}
		clone(): Course {
			return new Course({ ...this });
		}
	}
	class Student implements Clonable<Student> {
		firstName: string;
		courses: Course[];
		semester: Semester;
		constructor(me?: Student) {
			this.firstName = me?.firstName ?? '';
			this.courses = me?.courses ?? [];
			this.semester = me?.semester ?? new Semester();
		}
		clone(): Student {
			return new Student({ ...this });
		}
	}
	beforeEach(() => {
		originalStudent = new Student();
	});
	test('produce cloning ability', () => {
		expect(originalStudent.firstName).toBe('');
		expect(JSON.stringify(originalStudent.courses)).toBe('[]');
		expect(JSON.stringify(originalStudent.semester)).toBe('{"courses":[]}');

		const clonedStudent = produce(originalStudent);
		clonedStudent.firstName = 'clonedName';
		clonedStudent.courses.push(new Course({ courseName: 'algebra' }));
		clonedStudent.semester = new Semester({ courses: [new Course({ courseName: 'Math' })] });

		expect(clonedStudent instanceof Student).toBe(true);
		expect(originalStudent.firstName).toBe('');
		expect(JSON.stringify(originalStudent.courses)).toBe('[]');
		expect(JSON.stringify(originalStudent.semester)).toBe('{"courses":[]}');
	});
	test('produce mutating ability', () => {
		expect(originalStudent.firstName).toBe('');
		expect(JSON.stringify(originalStudent.courses)).toBe('[]');
		expect(JSON.stringify(originalStudent.semester)).toBe('{"courses":[]}');

		const clonedStudent = produce(originalStudent, (draft) => {
			draft.firstName = 'clonedName';
			draft.courses.push(new Course({ courseName: 'algebra' }));
			draft.semester = new Semester({ courses: [new Course({ courseName: 'Math' })] });
		});

		expect(clonedStudent instanceof Student).toBe(true);
		expect(originalStudent.firstName).toBe('');
		expect(JSON.stringify(originalStudent.courses)).toBe('[]');
		expect(JSON.stringify(originalStudent.semester)).toBe('{"courses":[]}');
	});
});
